//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 11-Jun-2008 by the VDM++ to JAVA Code Generator
// (v8.0.1b - Mon 28-Jan-2008 10:17:36)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.ast.imp;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import org.overturetool.ast.itf.*;
// ***** VDMTOOLS END Name=imports



public class OmlLetExpression extends OmlExpression implements IOmlLetExpression {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=ivDefinitionList KEEP=NO
  private Vector ivDefinitionList = null;
// ***** VDMTOOLS END Name=ivDefinitionList

// ***** VDMTOOLS START Name=ivExpression KEEP=NO
  private IOmlExpression ivExpression = null;
// ***** VDMTOOLS END Name=ivExpression


// ***** VDMTOOLS START Name=OmlLetExpression KEEP=NO
  public OmlLetExpression () throws CGException {
    try {

      ivDefinitionList = new Vector();
      ivExpression = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=OmlLetExpression


// ***** VDMTOOLS START Name=identity KEEP=NO
  public String identity () throws CGException {
    return new String("LetExpression");
  }
// ***** VDMTOOLS END Name=identity


// ***** VDMTOOLS START Name=accept KEEP=NO
  public void accept (final IOmlVisitor pVisitor) throws CGException {
    pVisitor.visitLetExpression((IOmlLetExpression) this);
  }
// ***** VDMTOOLS END Name=accept


// ***** VDMTOOLS START Name=OmlLetExpression KEEP=NO
  public OmlLetExpression (final Vector p1, final IOmlExpression p2) throws CGException {

    try {

      ivDefinitionList = new Vector();
      ivExpression = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      setDefinitionList(p1);
      setExpression((IOmlExpression) p2);
    }
  }
// ***** VDMTOOLS END Name=OmlLetExpression


// ***** VDMTOOLS START Name=OmlLetExpression KEEP=NO
  public OmlLetExpression (final Vector p1, final IOmlExpression p2, final Long line, final Long column) throws CGException {

    try {

      ivDefinitionList = new Vector();
      ivExpression = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      setDefinitionList(p1);
      setExpression((IOmlExpression) p2);
      setPosition(line, column);
    }
  }
// ***** VDMTOOLS END Name=OmlLetExpression


// ***** VDMTOOLS START Name=init KEEP=NO
  public void init (final HashMap data) throws CGException {

    {

      String fname = new String("definition_list");
      Boolean cond_4 = null;
      cond_4 = new Boolean(data.containsKey(fname));
      if (cond_4.booleanValue()) 
        setDefinitionList((Vector) data.get(fname));
    }
    {

      String fname = new String("expression");
      Boolean cond_13 = null;
      cond_13 = new Boolean(data.containsKey(fname));
      if (cond_13.booleanValue()) 
        setExpression((IOmlExpression) data.get(fname));
    }
  }
// ***** VDMTOOLS END Name=init


// ***** VDMTOOLS START Name=getDefinitionList KEEP=NO
  public Vector getDefinitionList () throws CGException {
    return ivDefinitionList;
  }
// ***** VDMTOOLS END Name=getDefinitionList


// ***** VDMTOOLS START Name=setDefinitionList KEEP=NO
  public void setDefinitionList (final Vector parg) throws CGException {
    ivDefinitionList = (Vector) UTIL.ConvertToList(UTIL.clone(parg));
  }
// ***** VDMTOOLS END Name=setDefinitionList


// ***** VDMTOOLS START Name=addDefinitionList KEEP=NO
  public void addDefinitionList (final IOmlNode parg) throws CGException {
    ivDefinitionList.add(parg);
  }
// ***** VDMTOOLS END Name=addDefinitionList


// ***** VDMTOOLS START Name=getExpression KEEP=NO
  public IOmlExpression getExpression () throws CGException {
    return (IOmlExpression) ivExpression;
  }
// ***** VDMTOOLS END Name=getExpression


// ***** VDMTOOLS START Name=setExpression KEEP=NO
  public void setExpression (final IOmlExpression parg) throws CGException {
    ivExpression = (IOmlExpression) UTIL.clone(parg);
  }
// ***** VDMTOOLS END Name=setExpression

  public String toString() {
	  String lst = new String();
	  int i, size = this.ivDefinitionList.size();
	  
	  for(i=0; i<size-1; i++) {
		  lst += this.ivDefinitionList.get(i).toString() + ",\n";
	  }
	  lst += this.ivDefinitionList.get(size-1).toString() + "\n";
	  
	  return "let " + lst + "in " + this.ivExpression.toString() + "\n";
  }
}
;
