//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 11-Jun-2008 by the VDM++ to JAVA Code Generator
// (v8.0.1b - Mon 28-Jan-2008 10:17:36)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.ast.imp;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import org.overturetool.ast.itf.*;
@SuppressWarnings(all) 
// ***** VDMTOOLS END Name=imports



public class OmlTypelessExplicitFunction extends OmlFunctionShape implements IOmlTypelessExplicitFunction {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=ivIdentifier KEEP=NO
  private String ivIdentifier = null;
// ***** VDMTOOLS END Name=ivIdentifier

// ***** VDMTOOLS START Name=ivParameterList KEEP=NO
  private Vector ivParameterList = null;
// ***** VDMTOOLS END Name=ivParameterList

// ***** VDMTOOLS START Name=ivBody KEEP=NO
  private IOmlFunctionBody ivBody = null;
// ***** VDMTOOLS END Name=ivBody

// ***** VDMTOOLS START Name=ivTrailer KEEP=NO
  private IOmlFunctionTrailer ivTrailer = null;
// ***** VDMTOOLS END Name=ivTrailer


// ***** VDMTOOLS START Name=OmlTypelessExplicitFunction KEEP=NO
  public OmlTypelessExplicitFunction () throws CGException {
    try {

      ivIdentifier = UTIL.ConvertToString(new String());
      ivParameterList = new Vector();
      ivBody = null;
      ivTrailer = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=OmlTypelessExplicitFunction


// ***** VDMTOOLS START Name=identity KEEP=NO
  public String identity () throws CGException {
    return new String("TypelessExplicitFunction");
  }
// ***** VDMTOOLS END Name=identity


// ***** VDMTOOLS START Name=accept KEEP=NO
  public void accept (final IOmlVisitor pVisitor) throws CGException {
    pVisitor.visitTypelessExplicitFunction((IOmlTypelessExplicitFunction) this);
  }
// ***** VDMTOOLS END Name=accept


// ***** VDMTOOLS START Name=OmlTypelessExplicitFunction KEEP=NO
  public OmlTypelessExplicitFunction (final String p1, final Vector p2, final IOmlFunctionBody p3, final IOmlFunctionTrailer p4) throws CGException {

    try {

      ivIdentifier = UTIL.ConvertToString(new String());
      ivParameterList = new Vector();
      ivBody = null;
      ivTrailer = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      setIdentifier(p1);
      setParameterList(p2);
      setBody((IOmlFunctionBody) p3);
      setTrailer((IOmlFunctionTrailer) p4);
    }
  }
// ***** VDMTOOLS END Name=OmlTypelessExplicitFunction


// ***** VDMTOOLS START Name=OmlTypelessExplicitFunction KEEP=NO
  public OmlTypelessExplicitFunction (final String p1, final Vector p2, final IOmlFunctionBody p3, final IOmlFunctionTrailer p4, final Long line, final Long column) throws CGException {

    try {

      ivIdentifier = UTIL.ConvertToString(new String());
      ivParameterList = new Vector();
      ivBody = null;
      ivTrailer = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      setIdentifier(p1);
      setParameterList(p2);
      setBody((IOmlFunctionBody) p3);
      setTrailer((IOmlFunctionTrailer) p4);
      setPosition(line, column);
    }
  }
// ***** VDMTOOLS END Name=OmlTypelessExplicitFunction


// ***** VDMTOOLS START Name=init KEEP=NO
  public void init (final HashMap data) throws CGException {

    {

      String fname = new String("identifier");
      Boolean cond_4 = null;
      cond_4 = new Boolean(data.containsKey(fname));
      if (cond_4.booleanValue()) 
        setIdentifier(UTIL.ConvertToString(data.get(fname)));
    }
    {

      String fname = new String("parameter_list");
      Boolean cond_13 = null;
      cond_13 = new Boolean(data.containsKey(fname));
      if (cond_13.booleanValue()) 
        setParameterList((Vector) data.get(fname));
    }
    {

      String fname = new String("body");
      Boolean cond_22 = null;
      cond_22 = new Boolean(data.containsKey(fname));
      if (cond_22.booleanValue()) 
        setBody((IOmlFunctionBody) data.get(fname));
    }
    {

      String fname = new String("trailer");
      Boolean cond_31 = null;
      cond_31 = new Boolean(data.containsKey(fname));
      if (cond_31.booleanValue()) 
        setTrailer((IOmlFunctionTrailer) data.get(fname));
    }
  }
// ***** VDMTOOLS END Name=init


// ***** VDMTOOLS START Name=getIdentifier KEEP=NO
  public String getIdentifier () throws CGException {
    return ivIdentifier;
  }
// ***** VDMTOOLS END Name=getIdentifier


// ***** VDMTOOLS START Name=setIdentifier KEEP=NO
  public void setIdentifier (final String parg) throws CGException {
    ivIdentifier = UTIL.ConvertToString(UTIL.clone(parg));
  }
// ***** VDMTOOLS END Name=setIdentifier


// ***** VDMTOOLS START Name=getParameterList KEEP=NO
  public Vector getParameterList () throws CGException {
    return ivParameterList;
  }
// ***** VDMTOOLS END Name=getParameterList


// ***** VDMTOOLS START Name=setParameterList KEEP=NO
  public void setParameterList (final Vector parg) throws CGException {
    ivParameterList = (Vector) UTIL.ConvertToList(UTIL.clone(parg));
  }
// ***** VDMTOOLS END Name=setParameterList


// ***** VDMTOOLS START Name=addParameterList KEEP=NO
  public void addParameterList (final IOmlNode parg) throws CGException {
    ivParameterList.add(parg);
  }
// ***** VDMTOOLS END Name=addParameterList


// ***** VDMTOOLS START Name=getBody KEEP=NO
  public IOmlFunctionBody getBody () throws CGException {
    return (IOmlFunctionBody) ivBody;
  }
// ***** VDMTOOLS END Name=getBody


// ***** VDMTOOLS START Name=setBody KEEP=NO
  public void setBody (final IOmlFunctionBody parg) throws CGException {
    ivBody = (IOmlFunctionBody) UTIL.clone(parg);
  }
// ***** VDMTOOLS END Name=setBody


// ***** VDMTOOLS START Name=getTrailer KEEP=NO
  public IOmlFunctionTrailer getTrailer () throws CGException {
    return (IOmlFunctionTrailer) ivTrailer;
  }
// ***** VDMTOOLS END Name=getTrailer


// ***** VDMTOOLS START Name=setTrailer KEEP=NO
  public void setTrailer (final IOmlFunctionTrailer parg) throws CGException {
    ivTrailer = (IOmlFunctionTrailer) UTIL.clone(parg);
  }
// ***** VDMTOOLS END Name=setTrailer

  //TODO: TypelessExplicitFunction
  public String toString() {
	  return "TODO: TypelessExplicitFunction";
  }
}
;
