


//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2009-10-16 by the VDM++ to JAVA Code Generator
// (v8.2.1b - Wed 15-Jul-2009 14:09:22)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.umltrans.uml2vdm;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import org.overturetool.ast.itf.*;
import org.overturetool.ast.imp.*;
import org.overturetool.api.io.*;
import org.overturetool.api.io.*;
import org.overturetool.api.*;
import org.overturetool.api.xml.*;
import org.overturetool.umltrans.*;
import org.overturetool.umltrans.api.Util;
import org.overturetool.umltrans.uml.*;
import org.overturetool.umltrans.uml2vdm.*;
import org.overturetool.umltrans.vdm2uml.*;
import org.overturetool.umltrans.api.*;
// ***** VDMTOOLS END Name=imports



@SuppressWarnings({"all","unchecked","unused"})
public class Xml2UmlModel extends XmlVisitor {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=result KEEP=NO
  public IUmlModel result = null;
// ***** VDMTOOLS END Name=result

// ***** VDMTOOLS START Name=primiticeTypes KEEP=NO
  private HashSet primiticeTypes = new HashSet();
// ***** VDMTOOLS END Name=primiticeTypes

// ***** VDMTOOLS START Name=classes KEEP=NO
  private HashSet classes = new HashSet();
// ***** VDMTOOLS END Name=classes

// ***** VDMTOOLS START Name=associations KEEP=NO
  private HashSet associations = new HashSet();
// ***** VDMTOOLS END Name=associations

// ***** VDMTOOLS START Name=constraints KEEP=NO
  private HashSet constraints = new HashSet();
// ***** VDMTOOLS END Name=constraints

// ***** VDMTOOLS START Name=classesTypeMap KEEP=NO
  private HashMap classesTypeMap = new HashMap();
// ***** VDMTOOLS END Name=classesTypeMap

// ***** VDMTOOLS START Name=collaborations KEEP=NO
  private HashSet collaborations = new HashSet();
// ***** VDMTOOLS END Name=collaborations

// ***** VDMTOOLS START Name=idToclassesMap KEEP=NO
  private HashMap idToclassesMap = new HashMap();
// ***** VDMTOOLS END Name=idToclassesMap

// ***** VDMTOOLS START Name=idToOperationMap KEEP=NO
  private HashMap idToOperationMap = new HashMap();
// ***** VDMTOOLS END Name=idToOperationMap

// ***** VDMTOOLS START Name=idToClallEventMap KEEP=NO
  private HashMap idToClallEventMap = new HashMap();
// ***** VDMTOOLS END Name=idToClallEventMap

// ***** VDMTOOLS START Name=lifeLineMap KEEP=NO
  private HashMap lifeLineMap = new HashMap();
// ***** VDMTOOLS END Name=lifeLineMap

// ***** VDMTOOLS START Name=mosMap KEEP=NO
  private HashMap mosMap = new HashMap();
// ***** VDMTOOLS END Name=mosMap

// ***** VDMTOOLS START Name=besMap KEEP=NO
  private HashMap besMap = new HashMap();
// ***** VDMTOOLS END Name=besMap

// ***** VDMTOOLS START Name=combiMap KEEP=NO
  private HashMap combiMap = new HashMap();
// ***** VDMTOOLS END Name=combiMap

// ***** VDMTOOLS START Name=log KEEP=NO
  private StatusLog log = null;
// ***** VDMTOOLS END Name=log


// ***** VDMTOOLS START Name=vdm_init_Xml2UmlModel KEEP=NO
  private void vdm_init_Xml2UmlModel () throws CGException {
    try {

      result = null;
      primiticeTypes = new HashSet();
      primiticeTypes.add(new String("char"));
      primiticeTypes.add(new String("int"));
      primiticeTypes.add(new String("bool"));
      primiticeTypes.add(new String("String"));
      primiticeTypes.add(new String("unlimitedNatural"));
      classes = new HashSet();
      associations = new HashSet();
      constraints = new HashSet();
      classesTypeMap = new HashMap();
      collaborations = new HashSet();
      idToclassesMap = new HashMap();
      idToOperationMap = new HashMap();
      idToClallEventMap = new HashMap();
      lifeLineMap = new HashMap();
      mosMap = new HashMap();
      besMap = new HashMap();
      combiMap = new HashMap();
      log = (StatusLog) new StatusLog();
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Xml2UmlModel


// ***** VDMTOOLS START Name=Xml2UmlModel KEEP=NO
  public Xml2UmlModel () throws CGException {
    vdm_init_Xml2UmlModel();
  }
// ***** VDMTOOLS END Name=Xml2UmlModel


// ***** VDMTOOLS START Name=Xml2UmlModel#1|StatusLog KEEP=NO
  public Xml2UmlModel (final StatusLog l) throws CGException {

    vdm_init_Xml2UmlModel();
    log = (StatusLog) UTIL.clone(l);
  }
// ***** VDMTOOLS END Name=Xml2UmlModel#1|StatusLog


// ***** VDMTOOLS START Name=VisitXmlDocument#1|XmlDocument KEEP=NO
  public void VisitXmlDocument (final XmlDocument doc) throws CGException {

    XmlEntity root = null;
    Vector unArg_2 = null;
    XmlEntityList tmpRec_3 = null;
    tmpRec_3 = doc.entities;
    unArg_2 = tmpRec_3.entities;
    root = (XmlEntity) unArg_2.get(0);
    Vector firstPackageAndRoot = null;
    Vector var1_5 = null;
    XmlEntityList tmpRec_6 = null;
    tmpRec_6 = root.entities;
    var1_5 = tmpRec_6.entities;
    Vector var2_8 = null;
    var2_8 = new Vector();
    var2_8.add(root);
    firstPackageAndRoot = (Vector) var1_5.clone();
    firstPackageAndRoot.addAll(var2_8);
    XmlEntity model = null;
    Vector unArg_10 = null;
    {

      Vector res_l_11 = new Vector();
      HashSet resBind_s_13 = new HashSet();
      HashSet riseq_17 = new HashSet();
      int max_18 = firstPackageAndRoot.size();
      for (int i_19 = 1; i_19 <= max_18; i_19++) 
        riseq_17.add(new Long(i_19));
      resBind_s_13 = riseq_17;
      Vector bind_l_12 = null;
      bind_l_12 = UTIL.Sort(resBind_s_13);
      Long i = null;
      for (Iterator enm_30 = bind_l_12.iterator(); enm_30.hasNext(); ) {

        Long e_15 = UTIL.NumberToLong(enm_30.next());
        i = e_15;
        Boolean pred_23 = null;
        String var1_24 = null;
        XmlEntity tmpRec_25 = null;
        if ((1 <= i.intValue()) && (i.intValue() <= firstPackageAndRoot.size())) 
          tmpRec_25 = (XmlEntity) firstPackageAndRoot.get(i.intValue() - 1);
        else 
          UTIL.RunTime("Run-Time Error:Illegal index");
        var1_24 = tmpRec_25.name;
        pred_23 = new Boolean(UTIL.equals(var1_24, new String("uml:Model")));
        if (pred_23.booleanValue()) {

          XmlEntity reselem_20 = null;
          if ((1 <= i.intValue()) && (i.intValue() <= firstPackageAndRoot.size())) 
            reselem_20 = (XmlEntity) firstPackageAndRoot.get(i.intValue() - 1);
          else 
            UTIL.RunTime("Run-Time Error:Illegal index");
          res_l_11.add(reselem_20);
        }
      }
      unArg_10 = res_l_11;
    }
    model = (XmlEntity) unArg_10.get(0);
    XmlEntity vdm_package = null;
    Vector unArg_31 = null;
    {

      Vector res_l_32 = new Vector();
      HashSet resBind_s_34 = new HashSet();
      Vector unArg_37 = null;
      XmlEntityList tmpRec_38 = null;
      tmpRec_38 = model.entities;
      unArg_37 = tmpRec_38.entities;
      HashSet riseq_40 = new HashSet();
      int max_41 = unArg_37.size();
      for (int i_42 = 1; i_42 <= max_41; i_42++) 
        riseq_40.add(new Long(i_42));
      resBind_s_34 = riseq_40;
      Vector bind_l_33 = null;
      bind_l_33 = UTIL.Sort(resBind_s_34);
      Long i = null;
      for (Iterator enm_56 = bind_l_33.iterator(); enm_56.hasNext(); ) {

        Long e_36 = UTIL.NumberToLong(enm_56.next());
        i = e_36;
        Boolean pred_48 = null;
        XmlEntity par_49 = null;
        Vector tmp_l_50 = null;
        XmlEntityList tmpRec_51 = null;
        tmpRec_51 = model.entities;
        tmp_l_50 = tmpRec_51.entities;
        if ((1 <= i.intValue()) && (i.intValue() <= tmp_l_50.size())) 
          par_49 = (XmlEntity) tmp_l_50.get(i.intValue() - 1);
        else 
          UTIL.RunTime("Run-Time Error:Illegal index");
        pred_48 = isAttributeType((XmlEntity) par_49, new String("uml:Package"));
        if (pred_48.booleanValue()) {

          XmlEntity reselem_43 = null;
          Vector tmp_l_44 = null;
          XmlEntityList tmpRec_45 = null;
          tmpRec_45 = model.entities;
          tmp_l_44 = tmpRec_45.entities;
          if ((1 <= i.intValue()) && (i.intValue() <= tmp_l_44.size())) 
            reselem_43 = (XmlEntity) tmp_l_44.get(i.intValue() - 1);
          else 
            UTIL.RunTime("Run-Time Error:Illegal index");
          res_l_32.add(reselem_43);
        }
      }
      unArg_31 = res_l_32;
    }
    vdm_package = (XmlEntity) unArg_31.get(0);
    {

      Vector pes = null;
      XmlEntityList tmpRec_59 = null;
      tmpRec_59 = vdm_package.entities;
      pes = tmpRec_59.entities;
      {

        HashMap rhs_61 = new HashMap();
        HashMap modmap_62 = new HashMap();
        HashMap res_m_65 = new HashMap();
        {

          HashSet e_set_84 = new HashSet();
          HashSet riseq_86 = new HashSet();
          int max_87 = pes.size();
          for (int i_88 = 1; i_88 <= max_87; i_88++) 
            riseq_86.add(new Long(i_88));
          e_set_84 = riseq_86;
          Long i = null;
          {
            for (Iterator enm_90 = e_set_84.iterator(); enm_90.hasNext(); ) {

              Long elem_89 = UTIL.NumberToLong(enm_90.next());
              i = elem_89;
              Boolean pred_78 = null;
              XmlEntity par_79 = null;
              if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                par_79 = (XmlEntity) pes.get(i.intValue() - 1);
              else 
                UTIL.RunTime("Run-Time Error:Illegal index");
              pred_78 = isAttributeType((XmlEntity) par_79, new String("uml:Class"));
              if (pred_78.booleanValue()) {

                String md_66 = null;
                XmlAttribute tmpRec_67 = null;
                XmlEntity par_68 = null;
                if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                  par_68 = (XmlEntity) pes.get(i.intValue() - 1);
                else 
                  UTIL.RunTime("Run-Time Error:Illegal index");
                tmpRec_67 = (XmlAttribute) getAttribute((XmlEntity) par_68, new String("xmi:id"));
                md_66 = tmpRec_67.val;
                String mr_72 = null;
                XmlAttribute tmpRec_73 = null;
                XmlEntity par_74 = null;
                if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                  par_74 = (XmlEntity) pes.get(i.intValue() - 1);
                else 
                  UTIL.RunTime("Run-Time Error:Illegal index");
                tmpRec_73 = (XmlAttribute) getAttribute((XmlEntity) par_74, new String("name"));
                mr_72 = tmpRec_73.val;
                res_m_65.put(md_66, mr_72);
              }
            }
          }
        }
        modmap_62 = res_m_65;
        rhs_61 = new HashMap(classesTypeMap);
        rhs_61.putAll(modmap_62);
        classesTypeMap = (HashMap) UTIL.clone(rhs_61);
        HashSet rhs_91 = new HashSet();
        HashSet var2_93 = new HashSet();
        HashSet res_s_94 = new HashSet();
        {

          HashSet e_set_114 = new HashSet();
          HashSet riseq_116 = new HashSet();
          int max_117 = pes.size();
          for (int i_118 = 1; i_118 <= max_117; i_118++) 
            riseq_116.add(new Long(i_118));
          e_set_114 = riseq_116;
          Long i = null;
          {
            for (Iterator enm_120 = e_set_114.iterator(); enm_120.hasNext(); ) {

              Long elem_119 = UTIL.NumberToLong(enm_120.next());
              i = elem_119;
              Boolean pred_99 = null;
              Boolean var1_100 = null;
              XmlEntity par_101 = null;
              if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                par_101 = (XmlEntity) pes.get(i.intValue() - 1);
              else 
                UTIL.RunTime("Run-Time Error:Illegal index");
              var1_100 = isAttributeType((XmlEntity) par_101, new String("uml:Class"));
              {
                if ((pred_99 = var1_100).booleanValue()) {

                  Boolean var2_105 = null;
                  String var1_106 = null;
                  XmlAttribute tmpRec_107 = null;
                  XmlEntity par_108 = null;
                  if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                    par_108 = (XmlEntity) pes.get(i.intValue() - 1);
                  else 
                    UTIL.RunTime("Run-Time Error:Illegal index");
                  tmpRec_107 = (XmlAttribute) getAttribute((XmlEntity) par_108, new String("name"));
                  var1_106 = tmpRec_107.val;
                  var2_105 = new Boolean(!primiticeTypes.contains(var1_106));
                  pred_99 = var2_105;
                }
              }
              if (pred_99.booleanValue()) {

                IUmlClass res_s_95 = null;
                XmlEntity par_96 = null;
                if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                  par_96 = (XmlEntity) pes.get(i.intValue() - 1);
                else 
                  UTIL.RunTime("Run-Time Error:Illegal index");
                res_s_95 = (IUmlClass) exstractClass((XmlEntity) par_96);
                res_s_94.add(res_s_95);
              }
            }
          }
        }
        var2_93 = res_s_94;
        rhs_91 = (HashSet) classes.clone();
        rhs_91.addAll(var2_93);
        classes = (HashSet) UTIL.clone(rhs_91);
        HashSet rhs_121 = new HashSet();
        HashSet var2_123 = new HashSet();
        HashSet res_s_124 = new HashSet();
        {

          HashSet e_set_141 = new HashSet();
          HashSet riseq_143 = new HashSet();
          int max_144 = pes.size();
          for (int i_145 = 1; i_145 <= max_144; i_145++) 
            riseq_143.add(new Long(i_145));
          e_set_141 = riseq_143;
          Long i = null;
          {
            for (Iterator enm_147 = e_set_141.iterator(); enm_147.hasNext(); ) {

              Long elem_146 = UTIL.NumberToLong(enm_147.next());
              i = elem_146;
              Boolean pred_129 = null;
              Boolean var1_130 = null;
              XmlEntity par_131 = null;
              if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                par_131 = (XmlEntity) pes.get(i.intValue() - 1);
              else 
                UTIL.RunTime("Run-Time Error:Illegal index");
              var1_130 = isAttributeType((XmlEntity) par_131, new String("uml:Association"));
              {
                if (!(pred_129 = var1_130).booleanValue()) {

                  Boolean var2_135 = null;
                  XmlEntity par_136 = null;
                  if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                    par_136 = (XmlEntity) pes.get(i.intValue() - 1);
                  else 
                    UTIL.RunTime("Run-Time Error:Illegal index");
                  var2_135 = isAttributeType((XmlEntity) par_136, new String("uml:Connector"));
                  pred_129 = var2_135;
                }
              }
              if (pred_129.booleanValue()) {

                IUmlAssociation res_s_125 = null;
                XmlEntity par_126 = null;
                if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                  par_126 = (XmlEntity) pes.get(i.intValue() - 1);
                else 
                  UTIL.RunTime("Run-Time Error:Illegal index");
                res_s_125 = (IUmlAssociation) build_uAssociation((XmlEntity) par_126);
                res_s_124.add(res_s_125);
              }
            }
          }
        }
        var2_123 = res_s_124;
        rhs_121 = (HashSet) associations.clone();
        rhs_121.addAll(var2_123);
        associations = (HashSet) UTIL.clone(rhs_121);
        HashSet rhs_148 = new HashSet();
        HashSet var2_150 = new HashSet();
        HashSet res_s_151 = new HashSet();
        {

          HashSet e_set_162 = new HashSet();
          HashSet riseq_164 = new HashSet();
          int max_165 = pes.size();
          for (int i_166 = 1; i_166 <= max_165; i_166++) 
            riseq_164.add(new Long(i_166));
          e_set_162 = riseq_164;
          Long i = null;
          {
            for (Iterator enm_168 = e_set_162.iterator(); enm_168.hasNext(); ) {

              Long elem_167 = UTIL.NumberToLong(enm_168.next());
              i = elem_167;
              Boolean pred_156 = null;
              XmlEntity par_157 = null;
              if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                par_157 = (XmlEntity) pes.get(i.intValue() - 1);
              else 
                UTIL.RunTime("Run-Time Error:Illegal index");
              pred_156 = isAttributeType((XmlEntity) par_157, new String("uml:Constraint"));
              if (pred_156.booleanValue()) {

                IUmlConstraint res_s_152 = null;
                XmlEntity par_153 = null;
                if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                  par_153 = (XmlEntity) pes.get(i.intValue() - 1);
                else 
                  UTIL.RunTime("Run-Time Error:Illegal index");
                res_s_152 = (IUmlConstraint) build_uConstraint((XmlEntity) par_153);
                res_s_151.add(res_s_152);
              }
            }
          }
        }
        var2_150 = res_s_151;
        rhs_148 = (HashSet) constraints.clone();
        rhs_148.addAll(var2_150);
        constraints = (HashSet) UTIL.clone(rhs_148);
        HashMap rhs_169 = new HashMap();
        HashSet par_170 = new HashSet();
        HashSet res_s_171 = new HashSet();
        {

          HashSet e_set_181 = new HashSet();
          HashSet riseq_183 = new HashSet();
          int max_184 = pes.size();
          for (int i_185 = 1; i_185 <= max_184; i_185++) 
            riseq_183.add(new Long(i_185));
          e_set_181 = riseq_183;
          Long i = null;
          {
            for (Iterator enm_187 = e_set_181.iterator(); enm_187.hasNext(); ) {

              Long elem_186 = UTIL.NumberToLong(enm_187.next());
              i = elem_186;
              Boolean pred_175 = null;
              XmlEntity par_176 = null;
              if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                par_176 = (XmlEntity) pes.get(i.intValue() - 1);
              else 
                UTIL.RunTime("Run-Time Error:Illegal index");
              pred_175 = isAttributeType((XmlEntity) par_176, new String("uml:CallEvent"));
              if (pred_175.booleanValue()) {

                XmlEntity res_s_172 = null;
                if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                  res_s_172 = (XmlEntity) pes.get(i.intValue() - 1);
                else 
                  UTIL.RunTime("Run-Time Error:Illegal index");
                res_s_171.add(res_s_172);
              }
            }
          }
        }
        par_170 = res_s_171;
        rhs_169 = buildCallEventMap(par_170);
        idToClallEventMap = (HashMap) UTIL.clone(rhs_169);
        HashSet rhs_188 = new HashSet();
        HashSet var2_190 = new HashSet();
        HashSet res_s_191 = new HashSet();
        {

          HashSet e_set_202 = new HashSet();
          HashSet riseq_204 = new HashSet();
          int max_205 = pes.size();
          for (int i_206 = 1; i_206 <= max_205; i_206++) 
            riseq_204.add(new Long(i_206));
          e_set_202 = riseq_204;
          Long i = null;
          {
            for (Iterator enm_208 = e_set_202.iterator(); enm_208.hasNext(); ) {

              Long elem_207 = UTIL.NumberToLong(enm_208.next());
              i = elem_207;
              Boolean pred_196 = null;
              XmlEntity par_197 = null;
              if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                par_197 = (XmlEntity) pes.get(i.intValue() - 1);
              else 
                UTIL.RunTime("Run-Time Error:Illegal index");
              pred_196 = isAttributeType((XmlEntity) par_197, new String("uml:Collaboration"));
              if (pred_196.booleanValue()) {

                IUmlCollaboration res_s_192 = null;
                XmlEntity par_193 = null;
                if ((1 <= i.intValue()) && (i.intValue() <= pes.size())) 
                  par_193 = (XmlEntity) pes.get(i.intValue() - 1);
                else 
                  UTIL.RunTime("Run-Time Error:Illegal index");
                res_s_192 = (IUmlCollaboration) build_uCollobration((XmlEntity) par_193);
                res_s_191.add(res_s_192);
              }
            }
          }
        }
        var2_190 = res_s_191;
        rhs_188 = (HashSet) collaborations.clone();
        rhs_188.addAll(var2_190);
        collaborations = (HashSet) UTIL.clone(rhs_188);
      }
    }
    UmlModel rhs_209 = null;
    String arg_210 = null;
    arg_210 = ((XmlAttribute) getAttribute((XmlEntity) vdm_package, new String("name"))).val;
    HashSet arg_211 = new HashSet();
    HashSet var1_215 = new HashSet();
    HashSet var1_216 = new HashSet();
    var1_216 = (HashSet) classes.clone();
    var1_216.addAll(associations);
    var1_215 = (HashSet) var1_216.clone();
    var1_215.addAll(constraints);
    arg_211 = (HashSet) var1_215.clone();
    arg_211.addAll(collaborations);
    rhs_209 = new UmlModel(arg_210, arg_211);
    result = (IUmlModel) UTIL.clone(rhs_209);
  }
// ***** VDMTOOLS END Name=VisitXmlDocument#1|XmlDocument


// ***** VDMTOOLS START Name=exstractClass#1|XmlEntity KEEP=NO
  private IUmlClass exstractClass (final XmlEntity e) throws CGException {

    String name = null;
    name = ((XmlAttribute) getAttribute((XmlEntity) e, new String("name"))).val;
    HashSet dBlocks = build_udefBlock((XmlEntity) e, name);
    Boolean vdm_abstract = null;
    if (hasAttribute((XmlEntity) e, new String("isAbstract")).booleanValue()) {

      String par_15 = null;
      par_15 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("isAbstract"))).val;
      vdm_abstract = (Boolean) StdLib.StringToBool(par_15);
    }
    else 
      vdm_abstract = new Boolean(false);
    Vector supers = null;
    {

      Vector eg = null;
      XmlEntityList tmpRec_22 = null;
      tmpRec_22 = e.entities;
      eg = tmpRec_22.entities;
      {

        Vector res_l_24 = new Vector();
        HashSet resBind_s_26 = new HashSet();
        HashSet riseq_30 = new HashSet();
        int max_31 = eg.size();
        for (int i_32 = 1; i_32 <= max_31; i_32++) 
          riseq_30.add(new Long(i_32));
        resBind_s_26 = riseq_30;
        Vector bind_l_25 = null;
        bind_l_25 = UTIL.Sort(resBind_s_26);
        Long i = null;
        for (Iterator enm_43 = bind_l_25.iterator(); enm_43.hasNext(); ) {

          Long e_28 = UTIL.NumberToLong(enm_43.next());
          i = e_28;
          Boolean pred_37 = null;
          XmlEntity par_38 = null;
          if ((1 <= i.intValue()) && (i.intValue() <= eg.size())) 
            par_38 = (XmlEntity) eg.get(i.intValue() - 1);
          else 
            UTIL.RunTime("Run-Time Error:Illegal index");
          pred_37 = isAttributeType((XmlEntity) par_38, new String("uml:Generalization"));
          if (pred_37.booleanValue()) {

            IUmlClassNameType reselem_33 = null;
            XmlEntity par_34 = null;
            if ((1 <= i.intValue()) && (i.intValue() <= eg.size())) 
              par_34 = (XmlEntity) eg.get(i.intValue() - 1);
            else 
              UTIL.RunTime("Run-Time Error:Illegal index");
            reselem_33 = (IUmlClassNameType) exstractGeneralization((XmlEntity) par_34);
            res_l_24.add(reselem_33);
          }
        }
        supers = res_l_24;
      }
    }
    IUmlVisibilityKind visibility = (IUmlVisibilityKind) new UmlVisibilityKind(UmlVisibilityKindQuotes.IQPUBLIC);
    Boolean isStatic = new Boolean(false);
    Boolean active = null;
    if (hasAttribute((XmlEntity) e, new String("isActive")).booleanValue()) {

      XmlAttribute a = (XmlAttribute) (XmlAttribute) getAttribute((XmlEntity) e, new String("isActive"));
      if ((!UTIL.equals(a, null))) {

        String par_60 = null;
        par_60 = a.val;
        active = (Boolean) StdLib.StringToBool(par_60);
      }
      else 
        active = new Boolean(false);
    }
    else 
      active = new Boolean(false);
    IUmlTemplateSignature template = null;
    String id = null;
    id = ((XmlAttribute) getAttribute((XmlEntity) e, new String("xmi:id"))).val;
    IUmlClass cls = (IUmlClass) new UmlClass(name, dBlocks, vdm_abstract, supers, visibility, isStatic, active, template);
    {

      idToclassesMap.put(id, cls);
      log.addNewClassInfo(name, id);
      return (IUmlClass) cls;
    }
  }
// ***** VDMTOOLS END Name=exstractClass#1|XmlEntity


// ***** VDMTOOLS START Name=exstractGeneralization#1|XmlEntity KEEP=NO
  private IUmlClassNameType exstractGeneralization (final XmlEntity e) throws CGException {

    String vdm_super = null;
    vdm_super = ((XmlAttribute) getAttribute((XmlEntity) e, new String("general"))).val;
    return (IUmlClassNameType) new UmlClassNameType(UTIL.ConvertToString(classesTypeMap.get(vdm_super)));
  }
// ***** VDMTOOLS END Name=exstractGeneralization#1|XmlEntity


// ***** VDMTOOLS START Name=build_udefBlock#2|XmlEntity|String KEEP=NO
  private HashSet build_udefBlock (final XmlEntity e, final String name) throws CGException {

    Vector eList = null;
    XmlEntityList tmpRec_5 = null;
    tmpRec_5 = e.entities;
    eList = tmpRec_5.entities;
    HashSet props = new HashSet();
    HashSet res_s_8 = new HashSet();
    {

      HashSet e_set_20 = new HashSet();
      HashSet riseq_22 = new HashSet();
      int max_23 = eList.size();
      for (int i_24 = 1; i_24 <= max_23; i_24++) 
        riseq_22.add(new Long(i_24));
      e_set_20 = riseq_22;
      Long i = null;
      {
        for (Iterator enm_26 = e_set_20.iterator(); enm_26.hasNext(); ) {

          Long elem_25 = UTIL.NumberToLong(enm_26.next());
          i = elem_25;
          Boolean pred_14 = null;
          XmlEntity par_15 = null;
          if ((1 <= i.intValue()) && (i.intValue() <= eList.size())) 
            par_15 = (XmlEntity) eList.get(i.intValue() - 1);
          else 
            UTIL.RunTime("Run-Time Error:Illegal index");
          pred_14 = isAttributeType((XmlEntity) par_15, new String("uml:Property"));
          if (pred_14.booleanValue()) {

            IUmlProperty res_s_9 = null;
            XmlEntity par_10 = null;
            if ((1 <= i.intValue()) && (i.intValue() <= eList.size())) 
              par_10 = (XmlEntity) eList.get(i.intValue() - 1);
            else 
              UTIL.RunTime("Run-Time Error:Illegal index");
            res_s_9 = (IUmlProperty) build_uProperty((XmlEntity) par_10, name);
            res_s_8.add(res_s_9);
          }
        }
      }
    }
    props = res_s_8;
    HashSet ops = new HashSet();
    HashSet res_s_28 = new HashSet();
    {

      HashSet e1_set_41 = new HashSet(eList);
      XmlEntity p = null;
      {
        for (Iterator enm_43 = e1_set_41.iterator(); enm_43.hasNext(); ) {

          XmlEntity elem_42 = (XmlEntity) enm_43.next();
          p = (XmlEntity) elem_42;
          Boolean pred_31 = null;
          {
            if (!(pred_31 = isAttributeType((XmlEntity) p, new String("uml:Operation"))).booleanValue()) {

              Boolean var2_35 = null;
              String var1_36 = null;
              var1_36 = p.name;
              var2_35 = new Boolean(UTIL.equals(var1_36, new String("ownedOperation")));
              pred_31 = var2_35;
            }
          }
          if (pred_31.booleanValue()) {
            res_s_28.add((IUmlOperation) build_uOperation((XmlEntity) p));
          }
        }
      }
    }
    ops = res_s_28;
    HashSet rexpr_44 = new HashSet();
    HashSet var1_45 = new HashSet();
    var1_45 = new HashSet();
    var1_45.add(new UmlOwnedProperties(props));
    HashSet var2_48 = new HashSet();
    var2_48 = new HashSet();
    var2_48.add(new UmlOwnedOperations(ops));
    rexpr_44 = (HashSet) var1_45.clone();
    rexpr_44.addAll(var2_48);
    return rexpr_44;
  }
// ***** VDMTOOLS END Name=build_udefBlock#2|XmlEntity|String


// ***** VDMTOOLS START Name=build_uProperty#2|XmlEntity|String KEEP=NO
  private IUmlProperty build_uProperty (final XmlEntity e, final String ownerClass) throws CGException {

    String name = null;
    if (hasAttribute((XmlEntity) e, new String("name")).booleanValue()) 
      name = ((XmlAttribute) getAttribute((XmlEntity) e, new String("name"))).val;
    else 
      name = new String("");
    IUmlVisibilityKind visibility = null;
    if (hasAttribute((XmlEntity) e, new String("visibility")).booleanValue()) 
      visibility = (IUmlVisibilityKind) (IUmlVisibilityKind) GetVisibility((XmlAttribute) (XmlAttribute) getAttribute((XmlEntity) e, new String("visibility")));
    else 
      visibility = (IUmlVisibilityKind) new UmlVisibilityKind(UmlVisibilityKindQuotes.IQPRIVATE);
    IUmlMultiplicityElement multiplicity = (IUmlMultiplicityElement) (IUmlMultiplicityElement) getMultiplicity((XmlEntity) e);
    IUmlType type = (IUmlType) (IUmlType) lookUpType((XmlEntity) e);
    Boolean isReadOnly = null;
    if (hasAttribute((XmlEntity) e, new String("isReadOnly")).booleanValue()) {

      String par_30 = null;
      par_30 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("isReadOnly"))).val;
      isReadOnly = (Boolean) StdLib.StringToBool(par_30);
    }
    else 
      isReadOnly = new Boolean(false);
    IUmlValueSpecification vdm_default = null;
    {

      HashSet dValue = new HashSet();
      HashSet res_s_37 = new HashSet();
      {

        Vector e_set_44 = null;
        XmlEntityList tmpRec_45 = null;
        tmpRec_45 = e.entities;
        e_set_44 = tmpRec_45.entities;
        XmlEntity el = null;
        {
          for (Iterator enm_48 = e_set_44.iterator(); enm_48.hasNext(); ) {

            XmlEntity elem_47 = (XmlEntity) enm_48.next();
            el = (XmlEntity) elem_47;
            Boolean pred_39 = null;
            String var1_40 = null;
            var1_40 = el.name;
            pred_39 = new Boolean(UTIL.equals(var1_40, new String("defaultValue")));
            if (pred_39.booleanValue()) {
              res_s_37.add(el);
            }
          }
        }
      }
      dValue = res_s_37;
      if (((new Long(dValue.size()).intValue()) > (new Long(0).intValue()))) {

        XmlEntity par_54 = null;
        {

          HashSet tmpSet_55 = new HashSet();
          tmpSet_55 = dValue;
          XmlEntity d = null;
          boolean succ_57 = false;
          for (Iterator enm_59 = tmpSet_55.iterator(); enm_59.hasNext() && !succ_57; ) {

            XmlEntity tmpElem_58 = (XmlEntity) enm_59.next();
            succ_57 = true;
            d = (XmlEntity) tmpElem_58;
          }
          if (!succ_57) 
            UTIL.RunTime("Run-Time Error:The binding environment was empty");
          par_54 = (XmlEntity) d;
        }
        vdm_default = (IUmlValueSpecification) getDefaultValue((XmlEntity) par_54);
      }
      else 
        vdm_default = null;
    }
    Boolean isComposite = new Boolean(false);
    Boolean isDerived = new Boolean(false);
    Boolean isStatic = new Boolean(false);
    IUmlType qualifier = null;
    return (IUmlProperty) new UmlProperty(name, visibility, multiplicity, type, isReadOnly, vdm_default, isComposite, isDerived, isStatic, ownerClass, qualifier);
  }
// ***** VDMTOOLS END Name=build_uProperty#2|XmlEntity|String


// ***** VDMTOOLS START Name=getDefaultValue#1|XmlEntity KEEP=NO
  private IUmlValueSpecification getDefaultValue (final XmlEntity e) throws CGException {

    String val = null;
    val = ((XmlAttribute) getAttribute((XmlEntity) e, new String("value"))).val;
    String typ = null;
    typ = ((XmlAttribute) getAttribute((XmlEntity) e, new String("xmi:type"))).val;
    Object rexpr_11 = null;
    boolean succ_12 = true;
    {

      succ_12 = true;
      if (!UTIL.equals(typ, new String("uml:LiteralString"))) 
        succ_12 = false;
      if (succ_12) 
        rexpr_11 = new UmlLiteralString(val);
    }
    if (!succ_12) {

      succ_12 = true;
      if (!UTIL.equals(typ, new String("uml:LiteralInteger"))) 
        succ_12 = false;
      if (succ_12) {

        Long arg_18 = null;
        arg_18 = UTIL.NumberToLong(StdLib.StringToInt(val));
        rexpr_11 = new UmlLiteralInteger(arg_18);
      }
    }
    if (!succ_12) 
      rexpr_11 = null;
    return (IUmlValueSpecification) rexpr_11;
  }
// ***** VDMTOOLS END Name=getDefaultValue#1|XmlEntity


// ***** VDMTOOLS START Name=getMultiplicity#1|XmlEntity KEEP=NO
  private IUmlMultiplicityElement getMultiplicity (final XmlEntity e) throws CGException {

    Vector eList = null;
    XmlEntityList tmpRec_4 = null;
    tmpRec_4 = e.entities;
    eList = tmpRec_4.entities;
    HashSet lowerSet = new HashSet();
    HashSet res_s_7 = new HashSet();
    {

      HashSet e1_set_22 = new HashSet(eList);
      XmlEntity el = null;
      {
        for (Iterator enm_24 = e1_set_22.iterator(); enm_24.hasNext(); ) {

          XmlEntity elem_23 = (XmlEntity) enm_24.next();
          el = (XmlEntity) elem_23;
          Boolean pred_12 = null;
          Boolean var1_13 = null;
          String var1_14 = null;
          var1_14 = el.name;
          var1_13 = new Boolean(UTIL.equals(var1_14, new String("lowerValue")));
          {
            if ((pred_12 = var1_13).booleanValue()) 
              pred_12 = hasAttribute((XmlEntity) e, new String("value"));
          }
          if (pred_12.booleanValue()) {

            String res_s_8 = null;
            res_s_8 = ((XmlAttribute) getAttribute((XmlEntity) el, new String("value"))).val;
            res_s_7.add(res_s_8);
          }
        }
      }
    }
    lowerSet = res_s_7;
    HashSet upperSet = new HashSet();
    HashSet res_s_26 = new HashSet();
    {

      HashSet e1_set_41 = new HashSet(eList);
      XmlEntity el = null;
      {
        for (Iterator enm_43 = e1_set_41.iterator(); enm_43.hasNext(); ) {

          XmlEntity elem_42 = (XmlEntity) enm_43.next();
          el = (XmlEntity) elem_42;
          Boolean pred_31 = null;
          Boolean var1_32 = null;
          String var1_33 = null;
          var1_33 = el.name;
          var1_32 = new Boolean(UTIL.equals(var1_33, new String("upperValue")));
          {
            if ((pred_31 = var1_32).booleanValue()) 
              pred_31 = hasAttribute((XmlEntity) e, new String("value"));
          }
          if (pred_31.booleanValue()) {

            String res_s_27 = null;
            res_s_27 = ((XmlAttribute) getAttribute((XmlEntity) el, new String("value"))).val;
            res_s_26.add(res_s_27);
          }
        }
      }
    }
    upperSet = res_s_26;
    Boolean cond_44 = null;
    {
      if ((cond_44 = new Boolean(new Long(upperSet.size()).intValue() == new Long(0).intValue())).booleanValue()) 
        cond_44 = new Boolean(new Long(lowerSet.size()).intValue() == new Long(0).intValue());
    }
    if (cond_44.booleanValue()) 
      return null;
    else {

      Long lower = null;
      if ((new Long(lowerSet.size()).intValue() == new Long(0).intValue())) 
        lower = new Long(0);
      else {

        HashSet tmpSet_60 = new HashSet();
        tmpSet_60 = lowerSet;
        String p = null;
        boolean succ_62 = false;
        for (Iterator enm_64 = tmpSet_60.iterator(); enm_64.hasNext() && !succ_62; ) {

          String tmpElem_63 = UTIL.ConvertToString(enm_64.next());
          succ_62 = true;
          p = tmpElem_63;
        }
        if (!succ_62) 
          UTIL.RunTime("Run-Time Error:The binding environment was empty");
        lower = UTIL.NumberToLong(StdLib.StringToInt(p));
      }
      Long upper = null;
      if ((new Long(upperSet.size()).intValue() == new Long(0).intValue())) 
        upper = null;
      else {

        HashSet tmpSet_72 = new HashSet();
        tmpSet_72 = upperSet;
        String p = null;
        boolean succ_74 = false;
        for (Iterator enm_76 = tmpSet_72.iterator(); enm_76.hasNext() && !succ_74; ) {

          String tmpElem_75 = UTIL.ConvertToString(enm_76.next());
          succ_74 = true;
          p = tmpElem_75;
        }
        if (!succ_74) 
          UTIL.RunTime("Run-Time Error:The binding environment was empty");
        upper = UTIL.NumberToLong(StdLib.StringToInt(p));
      }
      return (IUmlMultiplicityElement) new UmlMultiplicityElement(new Boolean(false), new Boolean(false), lower, upper);
    }
  }
// ***** VDMTOOLS END Name=getMultiplicity#1|XmlEntity


// ***** VDMTOOLS START Name=build_uOperation#1|XmlEntity KEEP=NO
  private IUmlOperation build_uOperation (final XmlEntity e) throws CGException {

    String tmpVal_3 = null;
    tmpVal_3 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("name"))).val;
    String name = null;
    name = tmpVal_3;
    IUmlVisibilityKind visibility = (IUmlVisibilityKind) (IUmlVisibilityKind) GetVisibility((XmlAttribute) (XmlAttribute) getAttribute((XmlEntity) e, new String("visibility")));
    IUmlMultiplicityElement multiplicity = (IUmlMultiplicityElement) new UmlMultiplicityElement(new Boolean(false), new Boolean(false), new Long(0), new Long(0));
    Boolean isQuery = null;
    if (hasAttribute((XmlEntity) e, new String("isQuery")).booleanValue()) {

      String par_21 = null;
      par_21 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("isQuery"))).val;
      isQuery = (Boolean) StdLib.StringToBool(par_21);
    }
    else 
      isQuery = new Boolean(false);
    IUmlType type = null;
    Boolean isStatic = null;
    if (hasAttribute((XmlEntity) e, new String("isStatic")).booleanValue()) {

      String par_31 = null;
      par_31 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("isStatic"))).val;
      isStatic = (Boolean) StdLib.StringToBool(par_31);
    }
    else 
      isStatic = new Boolean(false);
    String id = null;
    id = ((XmlAttribute) getAttribute((XmlEntity) e, new String("xmi:id"))).val;
    Vector params = CreateOperstionParameters((XmlEntity) e);
    UmlParameters parameters = null;
    if ((UTIL.equals(params, null))) 
      parameters = null;
    else 
      parameters = (UmlParameters) new UmlParameters(params);
    IUmlOperation operation = (IUmlOperation) new UmlOperation(name, visibility, multiplicity, isQuery, type, isStatic, parameters);
    {

      idToOperationMap.put(id, operation);
      return (IUmlOperation) operation;
    }
  }
// ***** VDMTOOLS END Name=build_uOperation#1|XmlEntity


// ***** VDMTOOLS START Name=CreateOperstionParameters#1|XmlEntity KEEP=NO
  protected Vector CreateOperstionParameters (final XmlEntity e) throws CGException {

    Vector tmpVal_3 = null;
    XmlEntityList tmpRec_4 = null;
    tmpRec_4 = e.entities;
    tmpVal_3 = tmpRec_4.entities;
    Vector elist = null;
    elist = tmpVal_3;
    Vector parms = null;
    {

      Vector res_l_7 = new Vector();
      HashSet resBind_s_9 = new HashSet();
      HashSet riseq_13 = new HashSet();
      int max_14 = elist.size();
      for (int i_15 = 1; i_15 <= max_14; i_15++) 
        riseq_13.add(new Long(i_15));
      resBind_s_9 = riseq_13;
      Vector bind_l_8 = null;
      bind_l_8 = UTIL.Sort(resBind_s_9);
      Long i = null;
      for (Iterator enm_47 = bind_l_8.iterator(); enm_47.hasNext(); ) {

        Long e_11 = UTIL.NumberToLong(enm_47.next());
        i = e_11;
        Boolean pred_40 = null;
        String var1_41 = null;
        XmlEntity tmpRec_42 = null;
        if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
          tmpRec_42 = (XmlEntity) elist.get(i.intValue() - 1);
        else 
          UTIL.RunTime("Run-Time Error:Illegal index");
        var1_41 = tmpRec_42.name;
        pred_40 = new Boolean(UTIL.equals(var1_41, new String("ownedParameter")));
        if (pred_40.booleanValue()) {

          UmlParameter reselem_16 = null;
          String arg_17 = null;
          XmlAttribute tmpRec_22 = null;
          XmlEntity par_23 = null;
          if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
            par_23 = (XmlEntity) elist.get(i.intValue() - 1);
          else 
            UTIL.RunTime("Run-Time Error:Illegal index");
          tmpRec_22 = (XmlAttribute) getAttribute((XmlEntity) par_23, new String("name"));
          arg_17 = tmpRec_22.val;
          IUmlType arg_18 = null;
          XmlEntity par_27 = null;
          if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
            par_27 = (XmlEntity) elist.get(i.intValue() - 1);
          else 
            UTIL.RunTime("Run-Time Error:Illegal index");
          arg_18 = (IUmlType) lookUpType((XmlEntity) par_27);
          IUmlParameterDirectionKind arg_21 = null;
          String par_34 = null;
          XmlAttribute tmpRec_35 = null;
          XmlEntity par_36 = null;
          if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
            par_36 = (XmlEntity) elist.get(i.intValue() - 1);
          else 
            UTIL.RunTime("Run-Time Error:Illegal index");
          tmpRec_35 = (XmlAttribute) getAttribute((XmlEntity) par_36, new String("direction"));
          par_34 = tmpRec_35.val;
          arg_21 = (IUmlParameterDirectionKind) ConvertParameterDirectionKind(par_34);
          reselem_16 = new UmlParameter(arg_17, arg_18, new UmlMultiplicityElement(new Boolean(false), new Boolean(false), new Long(1), new Long(1)), new String(""), arg_21);
          res_l_7.add(reselem_16);
        }
      }
      parms = res_l_7;
    }
    Vector rexpr_48 = null;
    if ((new Long(parms.size()).intValue() == new Long(0).intValue())) 
      rexpr_48 = null;
    else 
      rexpr_48 = parms;
    return rexpr_48;
  }
// ***** VDMTOOLS END Name=CreateOperstionParameters#1|XmlEntity


// ***** VDMTOOLS START Name=ConvertParameterDirectionKind#1|String KEEP=NO
  private IUmlParameterDirectionKind ConvertParameterDirectionKind (final String val) throws CGException {

    UmlParameterDirectionKind varRes_2 = null;
    boolean succ_3 = true;
    {

      succ_3 = true;
      if (!UTIL.equals(val, new String("in"))) 
        succ_3 = false;
      if (succ_3) 
        varRes_2 = (UmlParameterDirectionKind) new UmlParameterDirectionKind(UmlParameterDirectionKindQuotes.IQIN);
    }
    if (!succ_3) {

      succ_3 = true;
      if (!UTIL.equals(val, new String("out"))) 
        succ_3 = false;
      if (succ_3) 
        varRes_2 = (UmlParameterDirectionKind) new UmlParameterDirectionKind(UmlParameterDirectionKindQuotes.IQOUT);
    }
    if (!succ_3) {

      succ_3 = true;
      if (!UTIL.equals(val, new String("return"))) 
        succ_3 = false;
      if (succ_3) 
        varRes_2 = (UmlParameterDirectionKind) new UmlParameterDirectionKind(UmlParameterDirectionKindQuotes.IQRETURN);
    }
    if (!succ_3) {

      succ_3 = true;
      if (!UTIL.equals(val, new String("inout"))) 
        succ_3 = false;
      if (succ_3) 
        varRes_2 = (UmlParameterDirectionKind) new UmlParameterDirectionKind(UmlParameterDirectionKindQuotes.IQINOUT);
    }
    if (!succ_3) 
      UTIL.RunTime("Run-Time Error:No \'others\' branch in CasesExpr");
    return (IUmlParameterDirectionKind) varRes_2;
  }
// ***** VDMTOOLS END Name=ConvertParameterDirectionKind#1|String


// ***** VDMTOOLS START Name=build_uConstraint#1|XmlEntity KEEP=NO
  private IUmlConstraint build_uConstraint (final XmlEntity e) throws CGException {

    UmlConstraint varRes_2 = null;
    {

      Vector elist = null;
      XmlEntityList tmpRec_5 = null;
      tmpRec_5 = e.entities;
      elist = tmpRec_5.entities;
      HashSet ids = new HashSet();
      HashSet res_s_8 = new HashSet();
      {

        HashSet e1_set_18 = new HashSet(elist);
        XmlEntity p = null;
        {
          for (Iterator enm_20 = e1_set_18.iterator(); enm_20.hasNext(); ) {

            XmlEntity elem_19 = (XmlEntity) enm_20.next();
            p = (XmlEntity) elem_19;
            if (hasAttribute((XmlEntity) p, new String("xmi:idref")).booleanValue()) {

              String res_s_9 = null;
              res_s_9 = ((XmlAttribute) getAttribute((XmlEntity) p, new String("xmi:idref"))).val;
              res_s_8.add(res_s_9);
            }
          }
        }
      }
      ids = res_s_8;
      String specification = null;
      Vector unArg_22 = null;
      HashSet par_23 = new HashSet();
      HashSet res_s_24 = new HashSet();
      {

        HashSet e1_set_34 = new HashSet(elist);
        XmlEntity p = null;
        {
          for (Iterator enm_36 = e1_set_34.iterator(); enm_36.hasNext(); ) {

            XmlEntity elem_35 = (XmlEntity) enm_36.next();
            p = (XmlEntity) elem_35;
            Boolean pred_28 = null;
            String var1_29 = null;
            var1_29 = p.name;
            pred_28 = new Boolean(UTIL.equals(var1_29, new String("body")));
            if (pred_28.booleanValue()) {

              String res_s_25 = null;
              XmlData tmpRec_26 = null;
              tmpRec_26 = p.data;
              res_s_25 = tmpRec_26.data;
              res_s_24.add(res_s_25);
            }
          }
        }
      }
      par_23 = res_s_24;
      unArg_22 = (Vector) UTIL.ConvertToList(Util.SetToSeq(par_23));
      specification = UTIL.ConvertToString(unArg_22.get(0));
      varRes_2 = (UmlConstraint) new UmlConstraint(ids, new UmlLiteralString(specification));
    }
    return (IUmlConstraint) varRes_2;
  }
// ***** VDMTOOLS END Name=build_uConstraint#1|XmlEntity


// ***** VDMTOOLS START Name=build_uAssociation#1|XmlEntity KEEP=NO
  private IUmlAssociation build_uAssociation (final XmlEntity e) throws CGException {

    Vector tmpVal_3 = null;
    XmlEntityList tmpRec_4 = null;
    tmpRec_4 = e.entities;
    tmpVal_3 = tmpRec_4.entities;
    Vector elist = null;
    elist = tmpVal_3;
    HashSet props = new HashSet();
    HashSet res_s_7 = new HashSet();
    {

      HashSet e_set_17 = new HashSet();
      HashSet riseq_19 = new HashSet();
      int max_20 = elist.size();
      for (int i_21 = 1; i_21 <= max_20; i_21++) 
        riseq_19.add(new Long(i_21));
      e_set_17 = riseq_19;
      Long i = null;
      {
        for (Iterator enm_23 = e_set_17.iterator(); enm_23.hasNext(); ) {

          Long elem_22 = UTIL.NumberToLong(enm_23.next());
          i = elem_22;
          Boolean pred_11 = null;
          XmlEntity par_12 = null;
          if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
            par_12 = (XmlEntity) elist.get(i.intValue() - 1);
          else 
            UTIL.RunTime("Run-Time Error:Illegal index");
          pred_11 = isAttributeType((XmlEntity) par_12, new String("uml:Property"));
          if (pred_11.booleanValue()) {

            XmlEntity res_s_8 = null;
            if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
              res_s_8 = (XmlEntity) elist.get(i.intValue() - 1);
            else 
              UTIL.RunTime("Run-Time Error:Illegal index");
            res_s_7.add(res_s_8);
          }
        }
      }
    }
    props = res_s_7;
    HashSet ownedNavivableEnds = new HashSet();
    HashSet res_s_25 = new HashSet();
    {

      XmlEntity p = null;
      {
        for (Iterator enm_41 = props.iterator(); enm_41.hasNext(); ) {

          XmlEntity elem_40 = (XmlEntity) enm_41.next();
          p = (XmlEntity) elem_40;
          Boolean pred_29 = null;
          {
            if (!(pred_29 = new Boolean(!hasAttribute((XmlEntity) p, new String("name")).booleanValue())).booleanValue()) 
              pred_29 = hasAttributeValue((XmlEntity) p, new String("name"), new String(""));
          }
          if (pred_29.booleanValue()) {
            res_s_25.add((IUmlProperty) build_uProperty((XmlEntity) p, new String("")));
          }
        }
      }
    }
    ownedNavivableEnds = res_s_25;
    Vector one = null;
    one = (Vector) UTIL.ConvertToList(Util.SetToSeq(ownedNavivableEnds));
    IUmlType ownerClassType = null;
    Vector unArg_45 = null;
    {

      Vector res_l_46 = new Vector();
      HashSet resBind_s_48 = new HashSet();
      HashSet riseq_52 = new HashSet();
      int max_53 = one.size();
      for (int i_54 = 1; i_54 <= max_53; i_54++) 
        riseq_52.add(new Long(i_54));
      resBind_s_48 = riseq_52;
      Vector bind_l_47 = null;
      bind_l_47 = UTIL.Sort(resBind_s_48);
      Long i = null;
      for (Iterator enm_60 = bind_l_47.iterator(); enm_60.hasNext(); ) {

        Long e_50 = UTIL.NumberToLong(enm_60.next());
        i = e_50;
        IUmlType reselem_55 = null;
        IUmlProperty obj_56 = null;
        if ((1 <= i.intValue()) && (i.intValue() <= one.size())) 
          obj_56 = (IUmlProperty) one.get(i.intValue() - 1);
        else 
          UTIL.RunTime("Run-Time Error:Illegal index");
        reselem_55 = (IUmlType) obj_56.getType();
        res_l_46.add(reselem_55);
      }
      unArg_45 = res_l_46;
    }
    ownerClassType = (IUmlType) unArg_45.get(0);
    String tmpVal_61 = null;
    {

      IUmlClassNameType ct = (IUmlClassNameType) ownerClassType;
      tmpVal_61 = ct.getName();
    }
    String ownerClass = null;
    ownerClass = tmpVal_61;
    HashSet ownedEnds = new HashSet();
    HashSet res_s_65 = new HashSet();
    {

      XmlEntity p = null;
      {
        for (Iterator enm_83 = props.iterator(); enm_83.hasNext(); ) {

          XmlEntity elem_82 = (XmlEntity) enm_83.next();
          p = (XmlEntity) elem_82;
          Boolean pred_69 = null;
          {
            if ((pred_69 = hasAttribute((XmlEntity) p, new String("name"))).booleanValue()) {

              Boolean var2_73 = null;
              Long var1_74 = null;
              String unArg_75 = null;
              unArg_75 = ((XmlAttribute) getAttribute((XmlEntity) p, new String("name"))).val;
              var1_74 = new Long(unArg_75.length());
              var2_73 = new Boolean((var1_74.intValue()) > (new Long(0).intValue()));
              pred_69 = var2_73;
            }
          }
          if (pred_69.booleanValue()) {
            res_s_65.add((IUmlProperty) build_uProperty((XmlEntity) p, ownerClass));
          }
        }
      }
    }
    ownedEnds = res_s_65;
    String tmpVal_84 = null;
    if (hasAttribute((XmlEntity) e, new String("name")).booleanValue()) 
      tmpVal_84 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("name"))).val;
    else 
      tmpVal_84 = new String("");
    String name = null;
    name = tmpVal_84;
    String id = null;
    id = ((XmlAttribute) getAttribute((XmlEntity) e, new String("xmi:id"))).val;
    return (IUmlAssociation) new UmlAssociation(ownedEnds, ownedNavivableEnds, name, id);
  }
// ***** VDMTOOLS END Name=build_uAssociation#1|XmlEntity


// ***** VDMTOOLS START Name=lookUpType#1|XmlEntity KEEP=NO
  private IUmlType lookUpType (final XmlEntity e) throws CGException {

    Vector elist = null;
    XmlEntityList tmpRec_4 = null;
    tmpRec_4 = e.entities;
    elist = tmpRec_4.entities;
    HashSet typeOption1 = new HashSet();
    if (hasAttribute((XmlEntity) e, new String("type")).booleanValue()) {

      String enum_set_32 = null;
      enum_set_32 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("type"))).val;
      typeOption1 = new HashSet();
      typeOption1.add(enum_set_32);
    }
    else {

      HashSet res_s_11 = new HashSet();
      {

        HashSet e_set_25 = new HashSet();
        HashSet riseq_27 = new HashSet();
        int max_28 = elist.size();
        for (int i_29 = 1; i_29 <= max_28; i_29++) 
          riseq_27.add(new Long(i_29));
        e_set_25 = riseq_27;
        Long i = null;
        {
          for (Iterator enm_31 = e_set_25.iterator(); enm_31.hasNext(); ) {

            Long elem_30 = UTIL.NumberToLong(enm_31.next());
            i = elem_30;
            Boolean pred_18 = null;
            String var1_19 = null;
            XmlEntity tmpRec_20 = null;
            if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
              tmpRec_20 = (XmlEntity) elist.get(i.intValue() - 1);
            else 
              UTIL.RunTime("Run-Time Error:Illegal index");
            var1_19 = tmpRec_20.name;
            pred_18 = new Boolean(UTIL.equals(var1_19, new String("type")));
            if (pred_18.booleanValue()) {

              String res_s_12 = null;
              XmlAttribute tmpRec_13 = null;
              XmlEntity par_14 = null;
              if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
                par_14 = (XmlEntity) elist.get(i.intValue() - 1);
              else 
                UTIL.RunTime("Run-Time Error:Illegal index");
              tmpRec_13 = (XmlAttribute) getAttribute((XmlEntity) par_14, new String("xmi:idref"));
              res_s_12 = tmpRec_13.val;
              res_s_11.add(res_s_12);
            }
          }
        }
      }
      typeOption1 = res_s_11;
    }
    {

      HashSet tmpSet_36 = new HashSet();
      tmpSet_36 = typeOption1;
      String id = null;
      boolean succ_38 = false;
      for (Iterator enm_40 = tmpSet_36.iterator(); enm_40.hasNext() && !succ_38; ) {

        String tmpElem_39 = UTIL.ConvertToString(enm_40.next());
        succ_38 = true;
        id = tmpElem_39;
      }
      if (!succ_38) 
        UTIL.RunTime("Run-Time Error:The binding environment was empty");
      {

        String typeName = null;
        Boolean cond_44 = null;
        cond_44 = new Boolean(classesTypeMap.containsKey(id));
        if (cond_44.booleanValue()) 
          typeName = UTIL.ConvertToString(classesTypeMap.get(id));
        else 
          typeName = null;
        boolean succ_49 = true;
        {

          succ_49 = true;
          if (!UTIL.equals(typeName, null)) 
            succ_49 = false;
          if (succ_49) 
            return (IUmlType) new UmlIntegerType();
          else {

            succ_49 = true;
            if (!UTIL.equals(typeName, new String("String"))) 
              succ_49 = false;
            if (succ_49) 
              return (IUmlType) new UmlStringType();
            else {

              succ_49 = true;
              if (!UTIL.equals(typeName, new String("int"))) 
                succ_49 = false;
              if (succ_49) 
                return (IUmlType) new UmlIntegerType();
              else {

                succ_49 = true;
                if (!UTIL.equals(typeName, new String("bool"))) 
                  succ_49 = false;
                if (succ_49) 
                  return (IUmlType) new UmlBoolType();
                else {

                  succ_49 = true;
                  if (!UTIL.equals(typeName, new String("char"))) 
                    succ_49 = false;
                  if (succ_49) 
                    return (IUmlType) new UmlCharType();
                  else {

                    succ_49 = true;
                    if (!UTIL.equals(typeName, new String("unlimitedNatural"))) 
                      succ_49 = false;
                    if (succ_49) 
                      return (IUmlType) new UmlUnlimitedNatural();
                    else 
                      return (IUmlType) new UmlClassNameType(typeName);
                  }
                }
              }
            }
          }
        }
      }
    }
  }
// ***** VDMTOOLS END Name=lookUpType#1|XmlEntity


// ***** VDMTOOLS START Name=VisitXmlEntity#1|XmlEntity KEEP=NO
  public void VisitXmlEntity (final XmlEntity e) throws CGException {

    HashSet rhs_2 = new HashSet();
    HashSet var2_4 = new HashSet();
    HashSet res_s_5 = new HashSet();
    {

      HashSet e_set_19 = new HashSet();
      e_set_19 = new HashSet();
      e_set_19.add(e);
      XmlEntity entity = null;
      {
        for (Iterator enm_22 = e_set_19.iterator(); enm_22.hasNext(); ) {

          XmlEntity elem_21 = (XmlEntity) enm_22.next();
          entity = (XmlEntity) elem_21;
          Boolean pred_8 = null;
          {
            if ((pred_8 = isAttributeType((XmlEntity) entity, new String("uml:Class"))).booleanValue()) {

              Boolean var2_12 = null;
              String var1_13 = null;
              var1_13 = ((XmlAttribute) getAttribute((XmlEntity) entity, new String("name"))).val;
              var2_12 = new Boolean(!primiticeTypes.contains(var1_13));
              pred_8 = var2_12;
            }
          }
          if (pred_8.booleanValue()) {
            res_s_5.add((IUmlClass) exstractClass((XmlEntity) entity));
          }
        }
      }
    }
    var2_4 = res_s_5;
    rhs_2 = (HashSet) classes.clone();
    rhs_2.addAll(var2_4);
    classes = (HashSet) UTIL.clone(rhs_2);
    HashSet rhs_23 = new HashSet();
    HashSet var2_25 = new HashSet();
    HashSet res_s_26 = new HashSet();
    {

      HashSet e_set_33 = new HashSet();
      e_set_33 = new HashSet();
      e_set_33.add(e);
      XmlEntity entity = null;
      {
        for (Iterator enm_36 = e_set_33.iterator(); enm_36.hasNext(); ) {

          XmlEntity elem_35 = (XmlEntity) enm_36.next();
          entity = (XmlEntity) elem_35;
          if (isAttributeType((XmlEntity) entity, new String("uml:Association")).booleanValue()) {
            res_s_26.add((IUmlAssociation) build_uAssociation((XmlEntity) entity));
          }
        }
      }
    }
    var2_25 = res_s_26;
    rhs_23 = (HashSet) associations.clone();
    rhs_23.addAll(var2_25);
    associations = (HashSet) UTIL.clone(rhs_23);
  }
// ***** VDMTOOLS END Name=VisitXmlEntity#1|XmlEntity


// ***** VDMTOOLS START Name=hasAttribute#2|XmlEntity|String KEEP=NO
  private Boolean hasAttribute (final XmlEntity e, final String name) throws CGException {

    Boolean varRes_3 = null;
    {

      Vector list = null;
      XmlAttributeList tmpRec_6 = null;
      tmpRec_6 = e.attributes;
      list = tmpRec_6.attributes;
      boolean tmpQuant_8 = false;
      {

        HashSet e_set_16 = new HashSet();
        HashSet riseq_18 = new HashSet();
        int max_19 = list.size();
        for (int i_20 = 1; i_20 <= max_19; i_20++) 
          riseq_18.add(new Long(i_20));
        e_set_16 = riseq_18;
        Long i = null;
        {
          for (Iterator enm_22 = e_set_16.iterator(); enm_22.hasNext() && !tmpQuant_8; ) {

            Long elem_21 = UTIL.NumberToLong(enm_22.next());
            i = elem_21;
            Boolean pred_9 = null;
            String var1_10 = null;
            XmlAttribute tmpRec_11 = null;
            if ((1 <= i.intValue()) && (i.intValue() <= list.size())) 
              tmpRec_11 = (XmlAttribute) list.get(i.intValue() - 1);
            else 
              UTIL.RunTime("Run-Time Error:Illegal index");
            var1_10 = tmpRec_11.name;
            pred_9 = new Boolean(UTIL.equals(var1_10, name));
            if (pred_9.booleanValue()) 
              tmpQuant_8 = true;
          }
        }
      }
      varRes_3 = new Boolean(tmpQuant_8);
    }
    return varRes_3;
  }
// ***** VDMTOOLS END Name=hasAttribute#2|XmlEntity|String


// ***** VDMTOOLS START Name=hasAttributeValue#3|XmlEntity|String|String KEEP=NO
  private Boolean hasAttributeValue (final XmlEntity e, final String name, final String val) throws CGException {

    Boolean varRes_4 = null;
    {

      Vector list = null;
      XmlAttributeList tmpRec_7 = null;
      tmpRec_7 = e.attributes;
      list = tmpRec_7.attributes;
      boolean tmpQuant_9 = false;
      {

        HashSet e_set_24 = new HashSet();
        HashSet riseq_26 = new HashSet();
        int max_27 = list.size();
        for (int i_28 = 1; i_28 <= max_27; i_28++) 
          riseq_26.add(new Long(i_28));
        e_set_24 = riseq_26;
        Long i = null;
        {
          for (Iterator enm_30 = e_set_24.iterator(); enm_30.hasNext() && !tmpQuant_9; ) {

            Long elem_29 = UTIL.NumberToLong(enm_30.next());
            i = elem_29;
            Boolean pred_10 = null;
            Boolean var1_11 = null;
            String var1_12 = null;
            XmlAttribute tmpRec_13 = null;
            if ((1 <= i.intValue()) && (i.intValue() <= list.size())) 
              tmpRec_13 = (XmlAttribute) list.get(i.intValue() - 1);
            else 
              UTIL.RunTime("Run-Time Error:Illegal index");
            var1_12 = tmpRec_13.name;
            var1_11 = new Boolean(UTIL.equals(var1_12, name));
            {
              if ((pred_10 = var1_11).booleanValue()) {

                Boolean var2_17 = null;
                String var1_18 = null;
                XmlAttribute tmpRec_19 = null;
                if ((1 <= i.intValue()) && (i.intValue() <= list.size())) 
                  tmpRec_19 = (XmlAttribute) list.get(i.intValue() - 1);
                else 
                  UTIL.RunTime("Run-Time Error:Illegal index");
                var1_18 = tmpRec_19.val;
                var2_17 = new Boolean(UTIL.equals(var1_18, val));
                pred_10 = var2_17;
              }
            }
            if (pred_10.booleanValue()) 
              tmpQuant_9 = true;
          }
        }
      }
      varRes_4 = new Boolean(tmpQuant_9);
    }
    return varRes_4;
  }
// ***** VDMTOOLS END Name=hasAttributeValue#3|XmlEntity|String|String


// ***** VDMTOOLS START Name=isAttributeType#2|XmlEntity|String KEEP=NO
  private Boolean isAttributeType (final XmlEntity e, final String val) throws CGException {
    return hasAttributeValue((XmlEntity) e, new String("xmi:type"), val);
  }
// ***** VDMTOOLS END Name=isAttributeType#2|XmlEntity|String


// ***** VDMTOOLS START Name=getElementType#1|XmlEntity KEEP=NO
  private String getElementType (final XmlEntity e) throws CGException {

    String varRes_2 = null;
    if ((!UTIL.equals((XmlAttribute) getAttribute((XmlEntity) e, new String("xmi:type")), null))) 
      varRes_2 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("xmi:type"))).val;
    else 
      varRes_2 = e.name;
    return varRes_2;
  }
// ***** VDMTOOLS END Name=getElementType#1|XmlEntity


// ***** VDMTOOLS START Name=getAttribute#2|XmlEntity|String KEEP=NO
  private XmlAttribute getAttribute (final XmlEntity e, final String name) throws CGException {

    XmlAttribute varRes_3 = null;
    {

      Vector list = null;
      XmlAttributeList tmpRec_6 = null;
      tmpRec_6 = e.attributes;
      list = tmpRec_6.attributes;
      Vector attList = null;
      {

        Vector res_l_9 = new Vector();
        HashSet resBind_s_11 = new HashSet();
        HashSet riseq_15 = new HashSet();
        int max_16 = list.size();
        for (int i_17 = 1; i_17 <= max_16; i_17++) 
          riseq_15.add(new Long(i_17));
        resBind_s_11 = riseq_15;
        Vector bind_l_10 = null;
        bind_l_10 = UTIL.Sort(resBind_s_11);
        Long i = null;
        for (Iterator enm_28 = bind_l_10.iterator(); enm_28.hasNext(); ) {

          Long e_13 = UTIL.NumberToLong(enm_28.next());
          i = e_13;
          Boolean pred_21 = null;
          String var1_22 = null;
          XmlAttribute tmpRec_23 = null;
          if ((1 <= i.intValue()) && (i.intValue() <= list.size())) 
            tmpRec_23 = (XmlAttribute) list.get(i.intValue() - 1);
          else 
            UTIL.RunTime("Run-Time Error:Illegal index");
          var1_22 = tmpRec_23.name;
          pred_21 = new Boolean(UTIL.equals(var1_22, name));
          if (pred_21.booleanValue()) {

            XmlAttribute reselem_18 = null;
            if ((1 <= i.intValue()) && (i.intValue() <= list.size())) 
              reselem_18 = (XmlAttribute) list.get(i.intValue() - 1);
            else 
              UTIL.RunTime("Run-Time Error:Illegal index");
            res_l_9.add(reselem_18);
          }
        }
        attList = res_l_9;
      }
      if (((new Long(attList.size()).intValue()) > (new Long(0).intValue()))) 
        varRes_3 = (XmlAttribute) (XmlAttribute) attList.get(0);
      else 
        varRes_3 = null;
    }
    return (XmlAttribute) varRes_3;
  }
// ***** VDMTOOLS END Name=getAttribute#2|XmlEntity|String


// ***** VDMTOOLS START Name=GetVisibility#1|XmlAttribute KEEP=NO
  static private IUmlVisibilityKind GetVisibility (final XmlAttribute v) throws CGException {

    UmlVisibilityKind varRes_2 = null;
    if ((!UTIL.equals(v, null))) {

      String selRes_9 = null;
      selRes_9 = v.val;
      boolean succ_8 = true;
      {

        succ_8 = true;
        if (!UTIL.equals(selRes_9, new String("private"))) 
          succ_8 = false;
        if (succ_8) 
          varRes_2 = (UmlVisibilityKind) new UmlVisibilityKind(UmlVisibilityKindQuotes.IQPRIVATE);
      }
      if (!succ_8) {

        succ_8 = true;
        if (!UTIL.equals(selRes_9, new String("public"))) 
          succ_8 = false;
        if (succ_8) 
          varRes_2 = (UmlVisibilityKind) new UmlVisibilityKind(UmlVisibilityKindQuotes.IQPUBLIC);
      }
      if (!succ_8) {

        succ_8 = true;
        if (!UTIL.equals(selRes_9, new String("protected"))) 
          succ_8 = false;
        if (succ_8) 
          varRes_2 = (UmlVisibilityKind) new UmlVisibilityKind(UmlVisibilityKindQuotes.IQPROTECTED);
      }
      if (!succ_8) 
        UTIL.RunTime("Run-Time Error:No \'others\' branch in CasesExpr");
    }
    else 
      varRes_2 = (UmlVisibilityKind) new UmlVisibilityKind(UmlVisibilityKindQuotes.IQPRIVATE);
    return (IUmlVisibilityKind) varRes_2;
  }
// ***** VDMTOOLS END Name=GetVisibility#1|XmlAttribute


// ***** VDMTOOLS START Name=build_uCollobration#1|XmlEntity KEEP=NO
  private IUmlCollaboration build_uCollobration (final XmlEntity e) throws CGException {

    Vector tmpVal_3 = null;
    XmlEntityList tmpRec_4 = null;
    tmpRec_4 = e.entities;
    tmpVal_3 = tmpRec_4.entities;
    Vector elist = null;
    elist = tmpVal_3;
    HashSet interactions = new HashSet();
    HashSet res_s_7 = new HashSet();
    {

      HashSet e1_set_15 = new HashSet(elist);
      XmlEntity p = null;
      {
        for (Iterator enm_17 = e1_set_15.iterator(); enm_17.hasNext(); ) {

          XmlEntity elem_16 = (XmlEntity) enm_17.next();
          p = (XmlEntity) elem_16;
          if (isAttributeType((XmlEntity) p, new String("uml:Interaction")).booleanValue()) {
            res_s_7.add((IUmlInteraction) build_uInteraction((XmlEntity) p));
          }
        }
      }
    }
    interactions = res_s_7;
    return (IUmlCollaboration) new UmlCollaboration(interactions);
  }
// ***** VDMTOOLS END Name=build_uCollobration#1|XmlEntity


// ***** VDMTOOLS START Name=build_uInteraction#1|XmlEntity KEEP=NO
  private IUmlInteraction build_uInteraction (final XmlEntity e) throws CGException {

    Vector tmpVal_3 = null;
    XmlEntityList tmpRec_4 = null;
    tmpRec_4 = e.entities;
    tmpVal_3 = tmpRec_4.entities;
    Vector elist = null;
    elist = tmpVal_3;
    HashMap props = new HashMap();
    HashMap res_m_7 = new HashMap();
    {

      HashSet e1_set_20 = new HashSet(elist);
      XmlEntity p = null;
      {
        for (Iterator enm_22 = e1_set_20.iterator(); enm_22.hasNext(); ) {

          XmlEntity elem_21 = (XmlEntity) enm_22.next();
          p = (XmlEntity) elem_21;
          if (isAttributeType((XmlEntity) p, new String("uml:Property")).booleanValue()) {

            String md_8 = null;
            md_8 = ((XmlAttribute) getAttribute((XmlEntity) p, new String("xmi:id"))).val;
            res_m_7.put(md_8, (IUmlProperty) build_uProperty((XmlEntity) p, new String("")));
          }
        }
      }
    }
    props = res_m_7;
    {

      HashMap rhs_23 = new HashMap();
      HashMap modmap_24 = new HashMap();
      HashMap res_m_27 = new HashMap();
      {

        HashSet e1_set_50 = new HashSet(elist);
        XmlEntity p = null;
        {
          for (Iterator enm_52 = e1_set_50.iterator(); enm_52.hasNext(); ) {

            XmlEntity elem_51 = (XmlEntity) enm_52.next();
            p = (XmlEntity) elem_51;
            Boolean pred_44 = null;
            String var1_45 = null;
            var1_45 = p.name;
            pred_44 = new Boolean(UTIL.equals(var1_45, new String("lifeline")));
            if (pred_44.booleanValue()) {

              String md_28 = null;
              md_28 = ((XmlAttribute) getAttribute((XmlEntity) p, new String("xmi:id"))).val;
              UmlLifeLine mr_32 = null;
              String arg_33 = null;
              arg_33 = ((XmlAttribute) getAttribute((XmlEntity) p, new String("name"))).val;
              IUmlType arg_34 = null;
              IUmlProperty obj_38 = null;
              String tmppar_40 = null;
              tmppar_40 = ((XmlAttribute) getAttribute((XmlEntity) p, new String("represents"))).val;
              obj_38 = (IUmlProperty) props.get(tmppar_40);
              arg_34 = (IUmlType) obj_38.getType();
              mr_32 = new UmlLifeLine(arg_33, arg_34);
              res_m_27.put(md_28, mr_32);
            }
          }
        }
      }
      modmap_24 = res_m_27;
      rhs_23 = new HashMap(lifeLineMap);
      rhs_23.putAll(modmap_24);
      lifeLineMap = (HashMap) UTIL.clone(rhs_23);
      {

        String tmpVal_54 = null;
        tmpVal_54 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("name"))).val;
        String name = null;
        name = tmpVal_54;
        HashSet lifeLines = new HashSet();
        lifeLines.clear();
        lifeLines.addAll(lifeLineMap.values());
        HashSet mosfragments = new HashSet();
        HashSet res_s_61 = new HashSet();
        {

          HashSet e1_set_69 = new HashSet(elist);
          XmlEntity f = null;
          {
            for (Iterator enm_71 = e1_set_69.iterator(); enm_71.hasNext(); ) {

              XmlEntity elem_70 = (XmlEntity) enm_71.next();
              f = (XmlEntity) elem_70;
              if (isAttributeType((XmlEntity) f, new String("uml:MessageOccurrenceSpecification")).booleanValue()) {
                res_s_61.add((IUmlInteractionFragment) build_uFragment((XmlEntity) f));
              }
            }
          }
        }
        mosfragments = res_s_61;
        HashSet besfragments = new HashSet();
        HashSet res_s_73 = new HashSet();
        {

          HashSet e1_set_81 = new HashSet(elist);
          XmlEntity f = null;
          {
            for (Iterator enm_83 = e1_set_81.iterator(); enm_83.hasNext(); ) {

              XmlEntity elem_82 = (XmlEntity) enm_83.next();
              f = (XmlEntity) elem_82;
              if (isAttributeType((XmlEntity) f, new String("uml:BehaviorExecutionSpecification")).booleanValue()) {
                res_s_73.add((IUmlInteractionFragment) build_uFragment((XmlEntity) f));
              }
            }
          }
        }
        besfragments = res_s_73;
        HashSet combifragments = new HashSet();
        HashSet res_s_85 = new HashSet();
        {

          HashSet e1_set_93 = new HashSet(elist);
          XmlEntity f = null;
          {
            for (Iterator enm_95 = e1_set_93.iterator(); enm_95.hasNext(); ) {

              XmlEntity elem_94 = (XmlEntity) enm_95.next();
              f = (XmlEntity) elem_94;
              if (isAttributeType((XmlEntity) f, new String("uml:CombinedFragment")).booleanValue()) {
                res_s_85.add((IUmlInteractionFragment) build_uFragment((XmlEntity) f));
              }
            }
          }
        }
        combifragments = res_s_85;
        Vector messages = null;
        {

          Vector res_l_97 = new Vector();
          HashSet resBind_s_99 = new HashSet();
          HashSet riseq_103 = new HashSet();
          int max_104 = elist.size();
          for (int i_105 = 1; i_105 <= max_104; i_105++) 
            riseq_103.add(new Long(i_105));
          resBind_s_99 = riseq_103;
          Vector bind_l_98 = null;
          bind_l_98 = UTIL.Sort(resBind_s_99);
          Long i = null;
          for (Iterator enm_117 = bind_l_98.iterator(); enm_117.hasNext(); ) {

            Long e_101 = UTIL.NumberToLong(enm_117.next());
            i = e_101;
            Boolean pred_110 = null;
            String var1_111 = null;
            XmlEntity tmpRec_112 = null;
            if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
              tmpRec_112 = (XmlEntity) elist.get(i.intValue() - 1);
            else 
              UTIL.RunTime("Run-Time Error:Illegal index");
            var1_111 = tmpRec_112.name;
            pred_110 = new Boolean(UTIL.equals(var1_111, new String("message")));
            if (pred_110.booleanValue()) {

              IUmlMessage reselem_106 = null;
              XmlEntity par_107 = null;
              if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
                par_107 = (XmlEntity) elist.get(i.intValue() - 1);
              else 
                UTIL.RunTime("Run-Time Error:Illegal index");
              reselem_106 = (IUmlMessage) build_uMessage((XmlEntity) par_107);
              res_l_97.add(reselem_106);
            }
          }
          messages = res_l_97;
        }
        UmlInteraction rexpr_118 = null;
        HashSet arg_121 = new HashSet();
        HashSet var1_123 = new HashSet();
        var1_123 = (HashSet) mosfragments.clone();
        var1_123.addAll(besfragments);
        arg_121 = (HashSet) var1_123.clone();
        arg_121.addAll(combifragments);
        rexpr_118 = new UmlInteraction(name, lifeLines, arg_121, messages);
        return (IUmlInteraction) rexpr_118;
      }
    }
  }
// ***** VDMTOOLS END Name=build_uInteraction#1|XmlEntity


// ***** VDMTOOLS START Name=build_uMessage#1|XmlEntity KEEP=NO
  private IUmlMessage build_uMessage (final XmlEntity e) throws CGException {

    IUmlMessageKind messageKind = (IUmlMessageKind) new UmlMessageKind(UmlMessageKindQuotes.IQCOMPLETE);
    IUmlMessageSort messageSort = (IUmlMessageSort) new UmlMessageSort(UmlMessageSortQuotes.IQSYNCHCALL);
    IUmlMos mosSend = null;
    String tmppar_9 = null;
    tmppar_9 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("sendEvent"))).val;
    mosSend = (IUmlMos) mosMap.get(tmppar_9);
    IUmlMos mosRecive = null;
    String tmppar_15 = null;
    tmppar_15 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("receiveEvent"))).val;
    mosRecive = (IUmlMos) mosMap.get(tmppar_15);
    Vector args = new Vector();
    String name = null;
    IUmlOperation obj_21 = null;
    IUmlCallEvent obj_22 = null;
    obj_22 = (IUmlCallEvent) mosRecive.getEvent();
    obj_21 = (IUmlOperation) obj_22.getOperation();
    name = obj_21.getName();
    return (IUmlMessage) new UmlMessage(name, messageKind, messageSort, mosSend, mosRecive, args);
  }
// ***** VDMTOOLS END Name=build_uMessage#1|XmlEntity


// ***** VDMTOOLS START Name=build_uFragment#1|XmlEntity KEEP=NO
  private IUmlInteractionFragment build_uFragment (final XmlEntity e) throws CGException {

    boolean succ_2 = true;
    {

      succ_2 = true;
      if (!UTIL.equals(getElementType((XmlEntity) e), new String("uml:MessageOccurrenceSpecification"))) 
        succ_2 = false;
      if (succ_2) 
        return (IUmlInteractionFragment) (IUmlMos) build_uMos((XmlEntity) e);
      else {

        succ_2 = true;
        if (!UTIL.equals(getElementType((XmlEntity) e), new String("uml:BehaviorExecutionSpecification"))) 
          succ_2 = false;
        if (succ_2) 
          return (IUmlInteractionFragment) (IUmlBes) build_uBes((XmlEntity) e);
        else {

          succ_2 = true;
          if (!UTIL.equals(getElementType((XmlEntity) e), new String("uml:CombinedFragment"))) 
            succ_2 = false;
          if (succ_2) 
            return (IUmlInteractionFragment) (IUmlCombinedFragment) build_uCombi((XmlEntity) e);
          else {

            UTIL.RunTime("Run-Time Error:Can not evaluate an error statement");
throw new CGException(); //             return new IUmlInteractionFragment();
          }
        }
      }
    }
  }
// ***** VDMTOOLS END Name=build_uFragment#1|XmlEntity


// ***** VDMTOOLS START Name=build_uMos#1|XmlEntity KEEP=NO
  private IUmlMos build_uMos (final XmlEntity e) throws CGException {

    String name = null;
    name = ((XmlAttribute) getAttribute((XmlEntity) e, new String("name"))).val;
    IUmlMessage message = null;
    IUmlLifeLine lifeLines = null;
    {

      HashSet tmpSet_9 = new HashSet();
      HashSet res_s_13 = new HashSet();
      {

        HashSet e1_set_20 = new HashSet(GetCovered((XmlEntity) e));
        String c = null;
        {
          for (Iterator enm_22 = e1_set_20.iterator(); enm_22.hasNext(); ) {

            String elem_21 = UTIL.ConvertToString(enm_22.next());
            c = elem_21;
            res_s_13.add((IUmlLifeLine) lifeLineMap.get(c));
          }
        }
      }
      tmpSet_9 = res_s_13;
      IUmlLifeLine l = null;
      boolean succ_11 = false;
      for (Iterator enm_23 = tmpSet_9.iterator(); enm_23.hasNext() && !succ_11; ) {

        IUmlLifeLine tmpElem_12 = (IUmlLifeLine) enm_23.next();
        succ_11 = true;
        l = (IUmlLifeLine) tmpElem_12;
      }
      if (!succ_11) 
        UTIL.RunTime("Run-Time Error:The binding environment was empty");
      lifeLines = (IUmlLifeLine) l;
    }
    String id = null;
    id = ((XmlAttribute) getAttribute((XmlEntity) e, new String("xmi:id"))).val;
    IUmlCallEvent event = null;
    String tmppar_30 = null;
    tmppar_30 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("event"))).val;
    event = (IUmlCallEvent) idToClallEventMap.get(tmppar_30);
    UmlMos mos = (UmlMos) new UmlMos(name, message, lifeLines, event);
    {

      mosMap.put(id, mos);
      return (IUmlMos) mos;
    }
  }
// ***** VDMTOOLS END Name=build_uMos#1|XmlEntity


// ***** VDMTOOLS START Name=build_uBes#1|XmlEntity KEEP=NO
  private IUmlBes build_uBes (final XmlEntity e) throws CGException {

    String name = null;
    name = ((XmlAttribute) getAttribute((XmlEntity) e, new String("name"))).val;
    IUmlMos startOc = null;
    String tmppar_9 = null;
    tmppar_9 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("start"))).val;
    startOc = (IUmlMos) mosMap.get(tmppar_9);
    IUmlMos finishOc = null;
    String tmppar_15 = null;
    tmppar_15 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("finish"))).val;
    finishOc = (IUmlMos) mosMap.get(tmppar_15);
    HashSet covered = new HashSet();
    HashSet res_s_20 = new HashSet();
    {

      HashSet e1_set_27 = new HashSet(GetCovered((XmlEntity) e));
      String c = null;
      {
        for (Iterator enm_29 = e1_set_27.iterator(); enm_29.hasNext(); ) {

          String elem_28 = UTIL.ConvertToString(enm_29.next());
          c = elem_28;
          res_s_20.add((IUmlLifeLine) lifeLineMap.get(c));
        }
      }
    }
    covered = res_s_20;
    String id = null;
    id = ((XmlAttribute) getAttribute((XmlEntity) e, new String("xmi:id"))).val;
    UmlBes bes = (UmlBes) new UmlBes(name, startOc, finishOc, covered);
    {

      besMap.put(id, bes);
      return (IUmlBes) bes;
    }
  }
// ***** VDMTOOLS END Name=build_uBes#1|XmlEntity


// ***** VDMTOOLS START Name=build_uCombi#1|XmlEntity KEEP=NO
  private IUmlCombinedFragment build_uCombi (final XmlEntity e) throws CGException {

    Vector elist = null;
    XmlEntityList tmpRec_4 = null;
    tmpRec_4 = e.entities;
    elist = tmpRec_4.entities;
    String name = null;
    name = ((XmlAttribute) getAttribute((XmlEntity) e, new String("name"))).val;
    IUmlInteractionOperatorKind interactionOperatorKind = null;
    String par_11 = null;
    par_11 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("interactionOperator"))).val;
    interactionOperatorKind = (IUmlInteractionOperatorKind) GetIntOperationKind(par_11);
    Vector operands = null;
    {

      Vector res_l_16 = new Vector();
      HashSet resBind_s_18 = new HashSet();
      HashSet riseq_22 = new HashSet();
      int max_23 = elist.size();
      for (int i_24 = 1; i_24 <= max_23; i_24++) 
        riseq_22.add(new Long(i_24));
      resBind_s_18 = riseq_22;
      Vector bind_l_17 = null;
      bind_l_17 = UTIL.Sort(resBind_s_18);
      Long i = null;
      for (Iterator enm_36 = bind_l_17.iterator(); enm_36.hasNext(); ) {

        Long e_20 = UTIL.NumberToLong(enm_36.next());
        i = e_20;
        Boolean pred_29 = null;
        String var1_30 = null;
        XmlEntity tmpRec_31 = null;
        if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
          tmpRec_31 = (XmlEntity) elist.get(i.intValue() - 1);
        else 
          UTIL.RunTime("Run-Time Error:Illegal index");
        var1_30 = tmpRec_31.name;
        pred_29 = new Boolean(UTIL.equals(var1_30, new String("operand")));
        if (pred_29.booleanValue()) {

          IUmlInteractionOperand reselem_25 = null;
          XmlEntity par_26 = null;
          if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
            par_26 = (XmlEntity) elist.get(i.intValue() - 1);
          else 
            UTIL.RunTime("Run-Time Error:Illegal index");
          reselem_25 = (IUmlInteractionOperand) build_uOperand((XmlEntity) par_26);
          res_l_16.add(reselem_25);
        }
      }
      operands = res_l_16;
    }
    HashSet covered = new HashSet();
    HashSet res_s_38 = new HashSet();
    {

      HashSet e1_set_45 = new HashSet(GetCovered((XmlEntity) e));
      String c = null;
      {
        for (Iterator enm_47 = e1_set_45.iterator(); enm_47.hasNext(); ) {

          String elem_46 = UTIL.ConvertToString(enm_47.next());
          c = elem_46;
          res_s_38.add((IUmlLifeLine) lifeLineMap.get(c));
        }
      }
    }
    covered = res_s_38;
    String id = null;
    id = ((XmlAttribute) getAttribute((XmlEntity) e, new String("xmi:id"))).val;
    UmlCombinedFragment combi = (UmlCombinedFragment) new UmlCombinedFragment(name, interactionOperatorKind, operands, covered);
    {

      combiMap.put(id, combi);
      return (IUmlCombinedFragment) combi;
    }
  }
// ***** VDMTOOLS END Name=build_uCombi#1|XmlEntity


// ***** VDMTOOLS START Name=GetIntOperationKind#1|String KEEP=NO
  private IUmlInteractionOperatorKind GetIntOperationKind (final String text) throws CGException {

    UmlInteractionOperatorKind varRes_2 = null;
    boolean succ_3 = true;
    {

      succ_3 = true;
      if (!UTIL.equals(text, new String("alt"))) 
        succ_3 = false;
      if (succ_3) 
        varRes_2 = (UmlInteractionOperatorKind) new UmlInteractionOperatorKind(UmlInteractionOperatorKindQuotes.IQALT);
    }
    if (!succ_3) {

      succ_3 = true;
      if (!UTIL.equals(text, new String("loop"))) 
        succ_3 = false;
      if (succ_3) 
        varRes_2 = (UmlInteractionOperatorKind) new UmlInteractionOperatorKind(UmlInteractionOperatorKindQuotes.IQLOOP);
    }
    if (!succ_3) 
      UTIL.RunTime("Run-Time Error:No \'others\' branch in CasesExpr");
    return (IUmlInteractionOperatorKind) varRes_2;
  }
// ***** VDMTOOLS END Name=GetIntOperationKind#1|String


// ***** VDMTOOLS START Name=build_uOperand#1|XmlEntity KEEP=NO
  private IUmlInteractionOperand build_uOperand (final XmlEntity e) throws CGException {

    Vector elist = null;
    XmlEntityList tmpRec_4 = null;
    tmpRec_4 = e.entities;
    elist = tmpRec_4.entities;
    String name = new String("");
    Vector fragments = new Vector();
    HashSet covered = new HashSet();
    HashSet res_s_9 = new HashSet();
    {

      Vector e_set_14 = null;
      String par_15 = null;
      Vector unArg_16 = null;
      {

        Vector res_l_17 = new Vector();
        HashSet resBind_s_19 = new HashSet();
        HashSet riseq_23 = new HashSet();
        int max_24 = elist.size();
        for (int i_25 = 1; i_25 <= max_24; i_25++) 
          riseq_23.add(new Long(i_25));
        resBind_s_19 = riseq_23;
        Vector bind_l_18 = null;
        bind_l_18 = UTIL.Sort(resBind_s_19);
        Long i = null;
        for (Iterator enm_37 = bind_l_18.iterator(); enm_37.hasNext(); ) {

          Long e_21 = UTIL.NumberToLong(enm_37.next());
          i = e_21;
          Boolean pred_30 = null;
          XmlEntity par_31 = null;
          if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
            par_31 = (XmlEntity) elist.get(i.intValue() - 1);
          else 
            UTIL.RunTime("Run-Time Error:Illegal index");
          pred_30 = hasAttributeValue((XmlEntity) par_31, new String("extender"), new String("umltrans"));
          if (pred_30.booleanValue()) {

            String reselem_26 = null;
            XmlEntity par_27 = null;
            if ((1 <= i.intValue()) && (i.intValue() <= elist.size())) 
              par_27 = (XmlEntity) elist.get(i.intValue() - 1);
            else 
              UTIL.RunTime("Run-Time Error:Illegal index");
            reselem_26 = GetCoveredExtension((XmlEntity) par_27);
            res_l_17.add(reselem_26);
          }
        }
        unArg_16 = res_l_17;
      }
      String rdcseq_38 = new String();
      for (Iterator enm_41 = unArg_16.iterator(); enm_41.hasNext(); ) {

        String e_39 = UTIL.ConvertToString(enm_41.next());
        rdcseq_38 = rdcseq_38.concat(e_39);
      }
      par_15 = rdcseq_38;
      e_set_14 = (Vector) StdLib.Split(par_15, new Character(' '));
      String c = null;
      {
        for (Iterator enm_44 = e_set_14.iterator(); enm_44.hasNext(); ) {

          String elem_43 = UTIL.ConvertToString(enm_44.next());
          c = elem_43;
          res_s_9.add((IUmlMos) mosMap.get(c));
        }
      }
    }
    covered = res_s_9;
    IUmlInteractionConstraint guard = null;
    Boolean cond_47 = null;
    boolean tmpQuant_48 = false;
    {

      HashSet e1_set_55 = new HashSet(elist);
      XmlEntity gu = null;
      {
        for (Iterator enm_57 = e1_set_55.iterator(); enm_57.hasNext() && !tmpQuant_48; ) {

          XmlEntity elem_56 = (XmlEntity) enm_57.next();
          gu = (XmlEntity) elem_56;
          Boolean pred_49 = null;
          String var1_50 = null;
          var1_50 = gu.name;
          pred_49 = new Boolean(UTIL.equals(var1_50, new String("guard")));
          if (pred_49.booleanValue()) 
            tmpQuant_48 = true;
        }
      }
    }
    cond_47 = new Boolean(tmpQuant_48);
    if (cond_47.booleanValue()) {

      XmlEntity par_58 = null;
      {

        HashSet tmpSet_59 = new HashSet();
        HashSet res_s_63 = new HashSet();
        {

          HashSet e1_set_71 = new HashSet(elist);
          XmlEntity p = null;
          {
            for (Iterator enm_73 = e1_set_71.iterator(); enm_73.hasNext(); ) {

              XmlEntity elem_72 = (XmlEntity) enm_73.next();
              p = (XmlEntity) elem_72;
              Boolean pred_65 = null;
              String var1_66 = null;
              var1_66 = p.name;
              pred_65 = new Boolean(UTIL.equals(var1_66, new String("guard")));
              if (pred_65.booleanValue()) {
                res_s_63.add(p);
              }
            }
          }
        }
        tmpSet_59 = res_s_63;
        XmlEntity g = null;
        boolean succ_61 = false;
        for (Iterator enm_74 = tmpSet_59.iterator(); enm_74.hasNext() && !succ_61; ) {

          XmlEntity tmpElem_62 = (XmlEntity) enm_74.next();
          succ_61 = true;
          g = (XmlEntity) tmpElem_62;
        }
        if (!succ_61) 
          UTIL.RunTime("Run-Time Error:The binding environment was empty");
        par_58 = (XmlEntity) g;
      }
      guard = (IUmlInteractionConstraint) GetGuard((XmlEntity) par_58);
    }
    else 
      guard = null;
    return (IUmlInteractionOperand) new UmlInteractionOperand(name, fragments, covered, guard);
  }
// ***** VDMTOOLS END Name=build_uOperand#1|XmlEntity


// ***** VDMTOOLS START Name=GetCoveredExtension#1|XmlEntity KEEP=NO
  private String GetCoveredExtension (final XmlEntity e) throws CGException {

    String varRes_2 = null;
    {

      Vector elist = null;
      XmlEntityList tmpRec_5 = null;
      tmpRec_5 = e.entities;
      elist = tmpRec_5.entities;
      {

        HashSet tmpSet_7 = new HashSet();
        HashSet res_s_11 = new HashSet();
        {

          HashSet e1_set_21 = new HashSet(elist);
          XmlEntity co = null;
          {
            for (Iterator enm_23 = e1_set_21.iterator(); enm_23.hasNext(); ) {

              XmlEntity elem_22 = (XmlEntity) enm_23.next();
              co = (XmlEntity) elem_22;
              Boolean pred_15 = null;
              String var1_16 = null;
              var1_16 = co.name;
              pred_15 = new Boolean(UTIL.equals(var1_16, new String("covered")));
              if (pred_15.booleanValue()) {

                String res_s_12 = null;
                XmlData tmpRec_13 = null;
                tmpRec_13 = co.data;
                res_s_12 = tmpRec_13.data;
                res_s_11.add(res_s_12);
              }
            }
          }
        }
        tmpSet_7 = res_s_11;
        String p = null;
        boolean succ_9 = false;
        for (Iterator enm_24 = tmpSet_7.iterator(); enm_24.hasNext() && !succ_9; ) {

          String tmpElem_10 = UTIL.ConvertToString(enm_24.next());
          succ_9 = true;
          p = tmpElem_10;
        }
        if (!succ_9) 
          UTIL.RunTime("Run-Time Error:The binding environment was empty");
        varRes_2 = p;
      }
    }
    return varRes_2;
  }
// ***** VDMTOOLS END Name=GetCoveredExtension#1|XmlEntity


// ***** VDMTOOLS START Name=GetCovered#1|XmlEntity KEEP=NO
  private Vector GetCovered (final XmlEntity e) throws CGException {

    Vector varRes_2 = null;
    {

      String text = null;
      text = ((XmlAttribute) getAttribute((XmlEntity) e, new String("covered"))).val;
      varRes_2 = (Vector) StdLib.Split(text, new Character(' '));
    }
    return varRes_2;
  }
// ***** VDMTOOLS END Name=GetCovered#1|XmlEntity


// ***** VDMTOOLS START Name=GetGuard#1|XmlEntity KEEP=NO
  private IUmlInteractionConstraint GetGuard (final XmlEntity e) throws CGException {

    UmlInteractionConstraint varRes_2 = null;
    {

      Vector elist = null;
      XmlEntityList tmpRec_5 = null;
      tmpRec_5 = e.entities;
      elist = tmpRec_5.entities;
      IUmlValueSpecification minint = null;
      {

        HashSet tmpSet_8 = new HashSet();
        HashSet res_s_12 = new HashSet();
        {

          HashSet e1_set_21 = new HashSet(elist);
          XmlEntity p = null;
          {
            for (Iterator enm_23 = e1_set_21.iterator(); enm_23.hasNext(); ) {

              XmlEntity elem_22 = (XmlEntity) enm_23.next();
              p = (XmlEntity) elem_22;
              Boolean pred_15 = null;
              String var1_16 = null;
              var1_16 = p.name;
              pred_15 = new Boolean(UTIL.equals(var1_16, new String("minint")));
              if (pred_15.booleanValue()) {
                res_s_12.add((IUmlValueSpecification) getGuardConstraintValue((XmlEntity) p));
              }
            }
          }
        }
        tmpSet_8 = res_s_12;
        IUmlValueSpecification tmp = null;
        boolean succ_10 = false;
        for (Iterator enm_24 = tmpSet_8.iterator(); enm_24.hasNext() && !succ_10; ) {

          IUmlValueSpecification tmpElem_11 = (IUmlValueSpecification) enm_24.next();
          succ_10 = true;
          tmp = (IUmlValueSpecification) tmpElem_11;
        }
        if (!succ_10) 
          UTIL.RunTime("Run-Time Error:The binding environment was empty");
        minint = (IUmlValueSpecification) tmp;
      }
      IUmlValueSpecification maxint = null;
      {

        HashSet tmpSet_26 = new HashSet();
        HashSet res_s_30 = new HashSet();
        {

          HashSet e1_set_39 = new HashSet(elist);
          XmlEntity p = null;
          {
            for (Iterator enm_41 = e1_set_39.iterator(); enm_41.hasNext(); ) {

              XmlEntity elem_40 = (XmlEntity) enm_41.next();
              p = (XmlEntity) elem_40;
              Boolean pred_33 = null;
              String var1_34 = null;
              var1_34 = p.name;
              pred_33 = new Boolean(UTIL.equals(var1_34, new String("maxint")));
              if (pred_33.booleanValue()) {
                res_s_30.add((IUmlValueSpecification) getGuardConstraintValue((XmlEntity) p));
              }
            }
          }
        }
        tmpSet_26 = res_s_30;
        IUmlValueSpecification tmp = null;
        boolean succ_28 = false;
        for (Iterator enm_42 = tmpSet_26.iterator(); enm_42.hasNext() && !succ_28; ) {

          IUmlValueSpecification tmpElem_29 = (IUmlValueSpecification) enm_42.next();
          succ_28 = true;
          tmp = (IUmlValueSpecification) tmpElem_29;
        }
        if (!succ_28) 
          UTIL.RunTime("Run-Time Error:The binding environment was empty");
        maxint = (IUmlValueSpecification) tmp;
      }
      varRes_2 = (UmlInteractionConstraint) new UmlInteractionConstraint(minint, maxint);
    }
    return (IUmlInteractionConstraint) varRes_2;
  }
// ***** VDMTOOLS END Name=GetGuard#1|XmlEntity


// ***** VDMTOOLS START Name=getGuardConstraintValue#1|XmlEntity KEEP=NO
  private IUmlValueSpecification getGuardConstraintValue (final XmlEntity e) throws CGException {

    UmlLiteralInteger varRes_2 = null;
    Boolean cond_4 = null;
    {
      if ((cond_4 = hasAttribute((XmlEntity) e, new String("value"))).booleanValue()) 
        cond_4 = isAttributeType((XmlEntity) e, new String("uml:LiteralInteger"));
    }
    if (cond_4.booleanValue()) {

      Long arg_11 = null;
      String par_12 = null;
      par_12 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("value"))).val;
      arg_11 = UTIL.NumberToLong(StdLib.StringToInt(par_12));
      varRes_2 = new UmlLiteralInteger(arg_11);
    }
    else 
      varRes_2 = null;
    return (IUmlValueSpecification) varRes_2;
  }
// ***** VDMTOOLS END Name=getGuardConstraintValue#1|XmlEntity


// ***** VDMTOOLS START Name=buildCallEventMap#1|HashSet KEEP=NO
  private HashMap buildCallEventMap (final HashSet elist) throws CGException {

    HashMap m = new HashMap();
    HashMap res_m_4 = new HashMap();
    {

      XmlEntity e = null;
      {
        for (Iterator enm_19 = elist.iterator(); enm_19.hasNext(); ) {

          XmlEntity elem_18 = (XmlEntity) enm_19.next();
          e = (XmlEntity) elem_18;
          String md_5 = null;
          md_5 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("xmi:id"))).val;
          UmlCallEvent mr_9 = null;
          IUmlOperation arg_10 = null;
          String tmppar_12 = null;
          tmppar_12 = ((XmlAttribute) getAttribute((XmlEntity) e, new String("operation"))).val;
          arg_10 = (IUmlOperation) idToOperationMap.get(tmppar_12);
          mr_9 = new UmlCallEvent(arg_10);
          res_m_4.put(md_5, mr_9);
        }
      }
    }
    m = res_m_4;
    return m;
  }
// ***** VDMTOOLS END Name=buildCallEventMap#1|HashSet


// ***** VDMTOOLS START Name=VisitXmlAttribute#1|XmlAttribute KEEP=NO
  public void VisitXmlAttribute (final XmlAttribute var_1_1) throws CGException {}
// ***** VDMTOOLS END Name=VisitXmlAttribute#1|XmlAttribute


// ***** VDMTOOLS START Name=VisitXmlData#1|XmlData KEEP=NO
  public void VisitXmlData (final XmlData var_1_1) throws CGException {}
// ***** VDMTOOLS END Name=VisitXmlData#1|XmlData


// ***** VDMTOOLS START Name=setEncoding#1|String KEEP=NO
  public void setEncoding (final String encodingType) throws CGException {}
// ***** VDMTOOLS END Name=setEncoding#1|String

}
;