//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Sat 16-Aug-2008 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 06-Jun-2008 09:09:07)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.ast.imp;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import org.overturetool.ast.itf.*;
// ***** VDMTOOLS END Name=imports



public class OmlTraceSequenceDefinition extends OmlTraceDefinition implements IOmlTraceSequenceDefinition {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=ivDefs KEEP=NO
  private Vector ivDefs = null;
// ***** VDMTOOLS END Name=ivDefs


// ***** VDMTOOLS START Name=OmlTraceSequenceDefinition KEEP=NO
  public OmlTraceSequenceDefinition () throws CGException {
    try {
      ivDefs = new Vector();
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=OmlTraceSequenceDefinition


// ***** VDMTOOLS START Name=identity KEEP=NO
  public String identity () throws CGException {
    return new String("TraceSequenceDefinition");
  }
// ***** VDMTOOLS END Name=identity


// ***** VDMTOOLS START Name=accept KEEP=NO
  public void accept (final IOmlVisitor pVisitor) throws CGException {
    pVisitor.visitTraceSequenceDefinition((IOmlTraceSequenceDefinition) this);
  }
// ***** VDMTOOLS END Name=accept


// ***** VDMTOOLS START Name=OmlTraceSequenceDefinition KEEP=NO
  public OmlTraceSequenceDefinition (final Vector p1) throws CGException {

    try {
      ivDefs = new Vector();
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    setDefs(p1);
  }
// ***** VDMTOOLS END Name=OmlTraceSequenceDefinition


// ***** VDMTOOLS START Name=OmlTraceSequenceDefinition KEEP=NO
  public OmlTraceSequenceDefinition (final Vector p1, final Long line, final Long column) throws CGException {

    try {
      ivDefs = new Vector();
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      setDefs(p1);
      setPosition(line, column);
    }
  }
// ***** VDMTOOLS END Name=OmlTraceSequenceDefinition


// ***** VDMTOOLS START Name=init KEEP=NO
  public void init (final HashMap data) throws CGException {

    String fname = new String("defs");
    Boolean cond_4 = null;
    cond_4 = new Boolean(data.containsKey(fname));
    if (cond_4.booleanValue()) 
      setDefs((Vector) data.get(fname));
  }
// ***** VDMTOOLS END Name=init


// ***** VDMTOOLS START Name=getDefs KEEP=NO
  public Vector getDefs () throws CGException {
    return ivDefs;
  }
// ***** VDMTOOLS END Name=getDefs


// ***** VDMTOOLS START Name=setDefs KEEP=NO
  public void setDefs (final Vector parg) throws CGException {
    ivDefs = (Vector) UTIL.ConvertToList(UTIL.clone(parg));
  }
// ***** VDMTOOLS END Name=setDefs


// ***** VDMTOOLS START Name=addDefs KEEP=NO
  public void addDefs (final IOmlNode parg) throws CGException {
    ivDefs.add(parg);
  }
// ***** VDMTOOLS END Name=addDefs

}
;
