// this file is automatically generated by treegen. do not modify!

package org.overturetool.VDM2JavaCG.ast.java.imp;

// import the abstract tree interfaces
import org.overturetool.VDM2JavaCG.ast.java.itf.*;

public class JavaTailExpression extends JavaExpression implements IJavaTailExpression
{
	// private member variable (expression)
	private IJavaExpression m_expression = null;

	// public operation to retrieve the embedded private field value
	public IJavaExpression getExpression()
	{
		return m_expression;
	}

	// public operation to set the embedded private field value
	public void setExpression(IJavaExpression p_expression)
	{
		// consistency check (field must be non null!)
		assert(p_expression != null);

		// instantiate the member variable
		m_expression = p_expression;

		// set the parent of the parameter passed
		p_expression.setParent(this);
	}

	// default constructor
	public JavaTailExpression()
	{
		super();
		m_expression = null;
	}

	// auxiliary constructor
	public JavaTailExpression(
		IJavaExpression p_expression
	) {
		super();
		setExpression(p_expression);
	}

	// visitor support
	public void accept(IJavaVisitor pVisitor) { pVisitor.visitTailExpression(this); }

	// the identity function
	public String identify() { return "JavaTailExpression"; }
}
