// this file is automatically generated by treegen. do not modify!

package org.overturetool.VDM2JavaCG.ast.java.imp;

// import the abstract tree interfaces
import org.overturetool.VDM2JavaCG.ast.java.itf.*;

public class JavaInSetExpression extends JavaSetExpression implements IJavaInSetExpression
{
	// private member variable (owner)
	private IJavaExpression m_owner = null;

	// public operation to retrieve the embedded private field value
	public IJavaExpression getOwner()
	{
		return m_owner;
	}

	// public operation to set the embedded private field value
	public void setOwner(IJavaExpression p_owner)
	{
		// consistency check (field must be non null!)
		assert(p_owner != null);

		// instantiate the member variable
		m_owner = p_owner;

		// set the parent of the parameter passed
		p_owner.setParent(this);
	}

	// private member variable (elm)
	private IJavaExpression m_elm = null;

	// public operation to retrieve the embedded private field value
	public IJavaExpression getElm()
	{
		return m_elm;
	}

	// public operation to set the embedded private field value
	public void setElm(IJavaExpression p_elm)
	{
		// consistency check (field must be non null!)
		assert(p_elm != null);

		// instantiate the member variable
		m_elm = p_elm;

		// set the parent of the parameter passed
		p_elm.setParent(this);
	}

	// default constructor
	public JavaInSetExpression()
	{
		super();
		m_owner = null;
		m_elm = null;
	}

	// auxiliary constructor
	public JavaInSetExpression(
		IJavaExpression p_owner,
		IJavaExpression p_elm
	) {
		super();
		setOwner(p_owner);
		setElm(p_elm);
	}

	// visitor support
	public void accept(IJavaVisitor pVisitor) { pVisitor.visitInSetExpression(this); }

	// the identity function
	public String identify() { return "JavaInSetExpression"; }
}
