// this file is automatically generated by treegen. do not modify!

package org.overturetool.VDM2JavaCG.ast.java.imp;

// import the abstract tree interfaces
import org.overturetool.VDM2JavaCG.ast.java.itf.*;

public class JavaModifier extends JavaNode implements IJavaModifier
{
	// private member variable (Abstract)
	private Boolean m_Abstract = new Boolean(false);

	// public operation to retrieve the embedded private field value
	public Boolean getAbstract()
	{
		return m_Abstract;
	}

	// public operation to set the embedded private field value
	public void setAbstract(Boolean p_Abstract)
	{
		// consistency check (field must be non null!)
		assert(p_Abstract != null);

		// instantiate the member variable
		m_Abstract = p_Abstract;
	}

	// private member variable (Final)
	private Boolean m_Final = new Boolean(false);

	// public operation to retrieve the embedded private field value
	public Boolean getFinal()
	{
		return m_Final;
	}

	// public operation to set the embedded private field value
	public void setFinal(Boolean p_Final)
	{
		// consistency check (field must be non null!)
		assert(p_Final != null);

		// instantiate the member variable
		m_Final = p_Final;
	}

	// default constructor
	public JavaModifier()
	{
		super();
		m_Abstract = null;
		m_Final = null;
	}

	// auxiliary constructor
	public JavaModifier(
		Boolean p_Abstract,
		Boolean p_Final
	) {
		super();
		setAbstract(p_Abstract);
		setFinal(p_Final);
	}

	// visitor support
	public void accept(IJavaVisitor pVisitor) { pVisitor.visitModifier(this); }

	// the identity function
	public String identify() { return "JavaModifier"; }
}
