// this file is automatically generated by treegen. do not modify!

package org.overturetool.VDM2JavaCG.ast.java.imp;

// import the abstract tree interfaces
import org.overturetool.VDM2JavaCG.ast.java.itf.*;

public class JavaContinueStatement extends JavaStatement implements IJavaContinueStatement
{
	// default constructor
	public JavaContinueStatement()
	{
		super();
	}

	// visitor support
	public void accept(IJavaVisitor pVisitor) { pVisitor.visitContinueStatement(this); }

	// the identity function
	public String identify() { return "JavaContinueStatement"; }
}
