// this file is automatically generated by treegen. do not modify!

package org.overturetool.VDM2JavaCG.ast.java.imp;

// import the abstract tree interfaces
import org.overturetool.VDM2JavaCG.ast.java.itf.*;

// import java collection types
import java.util.*;

public class JavaCallObjectStatement extends JavaStatement implements IJavaCallObjectStatement
{
	// private member variable (object_designator)
	private IJavaObjectDesignator m_object_designator = null;

	// public operation to check optional type status
	public boolean hasObjectDesignator() { return (m_object_designator != null); };

	// public operation to retrieve the embedded private field value
	public IJavaObjectDesignator getObjectDesignator()
	{
		return m_object_designator;
	}

	// public operation to set the embedded private field value
	public void setObjectDesignator(IJavaObjectDesignator p_object_designator)
	{
		// instantiate the member variable
		m_object_designator = p_object_designator;

		// set the parent of the parameter passed
		p_object_designator.setParent(this);
	}

	// private member variable (name)
	private IJavaName m_name = null;

	// public operation to retrieve the embedded private field value
	public IJavaName getName()
	{
		return m_name;
	}

	// public operation to set the embedded private field value
	public void setName(IJavaName p_name)
	{
		// consistency check (field must be non null!)
		assert(p_name != null);

		// instantiate the member variable
		m_name = p_name;

		// set the parent of the parameter passed
		p_name.setParent(this);
	}

	// private member variable (expression_list)
	private List<IJavaExpression> m_expression_list = new Vector<IJavaExpression>();

	// public operation to retrieve the embedded private field value
	public List<IJavaExpression> getExpressionList()
	{
		return m_expression_list;
	}

	// public operation to set the embedded private field value
	public void setExpressionList(List<IJavaExpression> p_expression_list)
	{
		// consistency check (field must be non null!)
		assert(p_expression_list != null);

		// instantiate the member variable
		m_expression_list = p_expression_list;

		// set the parent of each element in the sequence parameter passed
		for (IJavaNode lnode: p_expression_list) lnode.setParent(this);
	}

	// default constructor
	public JavaCallObjectStatement()
	{
		super();
		m_object_designator = null;
		m_name = null;
		m_expression_list = null;
	}

	// auxiliary constructor
	public JavaCallObjectStatement(
		IJavaObjectDesignator p_object_designator,
		IJavaName p_name,
		List<IJavaExpression> p_expression_list
	) {
		super();
		setObjectDesignator(p_object_designator);
		setName(p_name);
		setExpressionList(p_expression_list);
	}

	// visitor support
	public void accept(IJavaVisitor pVisitor) { pVisitor.visitCallObjectStatement(this); }

	// the identity function
	public String identify() { return "JavaCallObjectStatement"; }
}
