// this file is automatically generated by treegen. do not modify!

package org.overturetool.VDM2JavaCG.ast.java.imp;

// import the abstract tree interfaces
import org.overturetool.VDM2JavaCG.ast.java.itf.*;

public class JavaDistIntersectionExpression extends JavaSetExpression implements IJavaDistIntersectionExpression
{
	// private member variable (setname)
	private IJavaExpression m_setname = null;

	// public operation to retrieve the embedded private field value
	public IJavaExpression getSetname()
	{
		return m_setname;
	}

	// public operation to set the embedded private field value
	public void setSetname(IJavaExpression p_setname)
	{
		// consistency check (field must be non null!)
		assert(p_setname != null);

		// instantiate the member variable
		m_setname = p_setname;

		// set the parent of the parameter passed
		p_setname.setParent(this);
	}

	// default constructor
	public JavaDistIntersectionExpression()
	{
		super();
		m_setname = null;
	}

	// auxiliary constructor
	public JavaDistIntersectionExpression(
		IJavaExpression p_setname
	) {
		super();
		setSetname(p_setname);
	}

	// visitor support
	public void accept(IJavaVisitor pVisitor) { pVisitor.visitDistIntersectionExpression(this); }

	// the identity function
	public String identify() { return "JavaDistIntersectionExpression"; }
}
