//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Mon 07-Jul-2008 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 06-Jun-2008 09:02:11)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.jml.ast.imp;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import org.overturetool.jml.ast.itf.*;
@SuppressWarnings(all) 
// ***** VDMTOOLS END Name=imports



public class JmlInterfaceInheritanceClause extends JmlNode implements IJmlInterfaceInheritanceClause {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=ivIdentifierList KEEP=NO
  private Vector ivIdentifierList = null;
// ***** VDMTOOLS END Name=ivIdentifierList


// ***** VDMTOOLS START Name=JmlInterfaceInheritanceClause KEEP=NO
  public JmlInterfaceInheritanceClause () throws CGException {
    try {
      ivIdentifierList = new Vector();
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=JmlInterfaceInheritanceClause


// ***** VDMTOOLS START Name=identity KEEP=NO
  public String identity () throws CGException {
    return new String("InterfaceInheritanceClause");
  }
// ***** VDMTOOLS END Name=identity


// ***** VDMTOOLS START Name=accept KEEP=NO
  public void accept (final IJmlVisitor pVisitor) throws CGException {
    pVisitor.visitInterfaceInheritanceClause((IJmlInterfaceInheritanceClause) this);
  }
// ***** VDMTOOLS END Name=accept


// ***** VDMTOOLS START Name=JmlInterfaceInheritanceClause KEEP=NO
  public JmlInterfaceInheritanceClause (final Vector p1) throws CGException {

    try {
      ivIdentifierList = new Vector();
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    setIdentifierList(p1);
  }
// ***** VDMTOOLS END Name=JmlInterfaceInheritanceClause


// ***** VDMTOOLS START Name=JmlInterfaceInheritanceClause KEEP=NO
  public JmlInterfaceInheritanceClause (final Vector p1, final Long line, final Long column) throws CGException {

    try {
      ivIdentifierList = new Vector();
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      setIdentifierList(p1);
      setPosition(line, column);
    }
  }
// ***** VDMTOOLS END Name=JmlInterfaceInheritanceClause


// ***** VDMTOOLS START Name=init KEEP=NO
  public void init (final HashMap data) throws CGException {

    String fname = new String("identifier_list");
    Boolean cond_4 = null;
    cond_4 = new Boolean(data.containsKey(fname));
    if (cond_4.booleanValue()) 
      setIdentifierList((Vector) data.get(fname));
  }
// ***** VDMTOOLS END Name=init


// ***** VDMTOOLS START Name=getIdentifierList KEEP=NO
  public Vector getIdentifierList () throws CGException {
    return ivIdentifierList;
  }
// ***** VDMTOOLS END Name=getIdentifierList


// ***** VDMTOOLS START Name=setIdentifierList KEEP=NO
  public void setIdentifierList (final Vector parg) throws CGException {
    ivIdentifierList = (Vector) UTIL.ConvertToList(UTIL.clone(parg));
  }
// ***** VDMTOOLS END Name=setIdentifierList


// ***** VDMTOOLS START Name=addIdentifierList KEEP=NO
  public void addIdentifierList (final String parg) throws CGException {
    ivIdentifierList.add(parg);
  }
// ***** VDMTOOLS END Name=addIdentifierList
  
  public String toString() {
	  
	  int size = this.ivIdentifierList.size();
	  
	  if(size == 0)
		  return "";
	  else {
		  
		  int i;
		  String tmp = new String();
		  
		  for(i = 0; i < size-1; i++) {
			  
			tmp += this.ivIdentifierList.get(i).toString() + ", ";
			
		  }
		  tmp += this.ivIdentifierList.get(size-1);
		  
		  return "implements " + tmp;
	  }
  }

}
;
