//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Mon 07-Jul-2008 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 06-Jun-2008 09:02:11)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.jml.ast.imp;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import org.overturetool.jml.ast.itf.*;
@SuppressWarnings(all) 
// ***** VDMTOOLS END Name=imports



public class JmlRequiresClause extends JmlTrailers implements IJmlRequiresClause {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=ivRequiresExpression KEEP=NO
  private IJmlExpression ivRequiresExpression = null;
// ***** VDMTOOLS END Name=ivRequiresExpression


// ***** VDMTOOLS START Name=JmlRequiresClause KEEP=NO
  public JmlRequiresClause () throws CGException {
    try {
      ivRequiresExpression = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=JmlRequiresClause


// ***** VDMTOOLS START Name=identity KEEP=NO
  public String identity () throws CGException {
    return new String("RequiresClause");
  }
// ***** VDMTOOLS END Name=identity


// ***** VDMTOOLS START Name=accept KEEP=NO
  public void accept (final IJmlVisitor pVisitor) throws CGException {
    pVisitor.visitRequiresClause((IJmlRequiresClause) this);
  }
// ***** VDMTOOLS END Name=accept


// ***** VDMTOOLS START Name=JmlRequiresClause KEEP=NO
  public JmlRequiresClause (final IJmlExpression p1) throws CGException {

    try {
      ivRequiresExpression = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    setRequiresExpression((IJmlExpression) p1);
  }
// ***** VDMTOOLS END Name=JmlRequiresClause


// ***** VDMTOOLS START Name=JmlRequiresClause KEEP=NO
  public JmlRequiresClause (final IJmlExpression p1, final Long line, final Long column) throws CGException {

    try {
      ivRequiresExpression = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      setRequiresExpression((IJmlExpression) p1);
      setPosition(line, column);
    }
  }
// ***** VDMTOOLS END Name=JmlRequiresClause


// ***** VDMTOOLS START Name=init KEEP=NO
  public void init (final HashMap data) throws CGException {

    String fname = new String("requires_expression");
    Boolean cond_4 = null;
    cond_4 = new Boolean(data.containsKey(fname));
    if (cond_4.booleanValue()) 
      setRequiresExpression((IJmlExpression) data.get(fname));
  }
// ***** VDMTOOLS END Name=init


// ***** VDMTOOLS START Name=getRequiresExpression KEEP=NO
  public IJmlExpression getRequiresExpression () throws CGException {
    return (IJmlExpression) ivRequiresExpression;
  }
// ***** VDMTOOLS END Name=getRequiresExpression


// ***** VDMTOOLS START Name=setRequiresExpression KEEP=NO
  public void setRequiresExpression (final IJmlExpression parg) throws CGException {
    ivRequiresExpression = (IJmlExpression) UTIL.clone(parg);
  }
// ***** VDMTOOLS END Name=setRequiresExpression
  
public String toString() {
	  
	  return "requires " + this.ivRequiresExpression.toString() + ";";
  } 

}
;
