//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Mon 07-Jul-2008 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 06-Jun-2008 09:02:11)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.jml.ast.imp;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import org.overturetool.jml.ast.itf.*;
// ***** VDMTOOLS END Name=imports



public class JmlSeqValueType extends JmlType implements IJmlSeqValueType {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=ivType KEEP=NO
  private IJmlType ivType = null;
// ***** VDMTOOLS END Name=ivType

// ***** VDMTOOLS START Name=ivLimit KEEP=NO
  private Long ivLimit = null;
// ***** VDMTOOLS END Name=ivLimit


// ***** VDMTOOLS START Name=JmlSeqValueType KEEP=NO
  public JmlSeqValueType () throws CGException {
    try {

      ivType = null;
      ivLimit = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=JmlSeqValueType


// ***** VDMTOOLS START Name=identity KEEP=NO
  public String identity () throws CGException {
    return new String("SeqValueType");
  }
// ***** VDMTOOLS END Name=identity


// ***** VDMTOOLS START Name=accept KEEP=NO
  public void accept (final IJmlVisitor pVisitor) throws CGException {
    pVisitor.visitSeqValueType((IJmlSeqValueType) this);
  }
// ***** VDMTOOLS END Name=accept


// ***** VDMTOOLS START Name=JmlSeqValueType KEEP=NO
  public JmlSeqValueType (final IJmlType p1, final Long p2) throws CGException {

    try {

      ivType = null;
      ivLimit = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      setType((IJmlType) p1);
      setLimit(p2);
    }
  }
// ***** VDMTOOLS END Name=JmlSeqValueType


// ***** VDMTOOLS START Name=JmlSeqValueType KEEP=NO
  public JmlSeqValueType (final IJmlType p1, final Long p2, final Long line, final Long column) throws CGException {

    try {

      ivType = null;
      ivLimit = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      setType((IJmlType) p1);
      setLimit(p2);
      setPosition(line, column);
    }
  }
// ***** VDMTOOLS END Name=JmlSeqValueType


// ***** VDMTOOLS START Name=init KEEP=NO
  public void init (final HashMap data) throws CGException {

    {

      String fname = new String("type");
      Boolean cond_4 = null;
      cond_4 = new Boolean(data.containsKey(fname));
      if (cond_4.booleanValue()) 
        setType((IJmlType) data.get(fname));
    }
    {

      String fname = new String("limit");
      Boolean cond_13 = null;
      cond_13 = new Boolean(data.containsKey(fname));
      if (cond_13.booleanValue()) 
        setLimit(UTIL.NumberToLong(data.get(fname)));
    }
  }
// ***** VDMTOOLS END Name=init


// ***** VDMTOOLS START Name=getType KEEP=NO
  public IJmlType getType () throws CGException {
    return (IJmlType) ivType;
  }
// ***** VDMTOOLS END Name=getType


// ***** VDMTOOLS START Name=setType KEEP=NO
  public void setType (final IJmlType parg) throws CGException {
    ivType = (IJmlType) UTIL.clone(parg);
  }
// ***** VDMTOOLS END Name=setType


// ***** VDMTOOLS START Name=getLimit KEEP=NO
  public Long getLimit () throws CGException {
    return ivLimit;
  }
// ***** VDMTOOLS END Name=getLimit


// ***** VDMTOOLS START Name=setLimit KEEP=NO
  public void setLimit (final Long parg) throws CGException {
    ivLimit = UTIL.NumberToLong(UTIL.clone(parg));
  }
// ***** VDMTOOLS END Name=setLimit
  
  public String toString() {
	  
	  //TODO
	  return "JMLValueSequence";
  }

}
;
