//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Mon 07-Jul-2008 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 06-Jun-2008 09:02:11)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.jml.ast.imp;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import org.overturetool.jml.ast.itf.*;
// ***** VDMTOOLS END Name=imports



public class JmlValueDefinition extends JmlNode implements IJmlValueDefinition {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=ivAccess KEEP=NO
  private IJmlAccessDefinition ivAccess = null;
// ***** VDMTOOLS END Name=ivAccess

// ***** VDMTOOLS START Name=ivStaticMod KEEP=NO
  private Boolean ivStaticMod = null;
// ***** VDMTOOLS END Name=ivStaticMod

// ***** VDMTOOLS START Name=ivFinalMod KEEP=NO
  private Boolean ivFinalMod = null;
// ***** VDMTOOLS END Name=ivFinalMod

// ***** VDMTOOLS START Name=ivShape KEEP=NO
  private IJmlValueShape ivShape = null;
// ***** VDMTOOLS END Name=ivShape


// ***** VDMTOOLS START Name=JmlValueDefinition KEEP=NO
  public JmlValueDefinition () throws CGException {
    try {

      ivAccess = null;
      ivStaticMod = null;
      ivFinalMod = null;
      ivShape = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=JmlValueDefinition


// ***** VDMTOOLS START Name=identity KEEP=NO
  public String identity () throws CGException {
    return new String("ValueDefinition");
  }
// ***** VDMTOOLS END Name=identity


// ***** VDMTOOLS START Name=accept KEEP=NO
  public void accept (final IJmlVisitor pVisitor) throws CGException {
    pVisitor.visitValueDefinition((IJmlValueDefinition) this);
  }
// ***** VDMTOOLS END Name=accept


// ***** VDMTOOLS START Name=JmlValueDefinition KEEP=NO
  public JmlValueDefinition (final IJmlAccessDefinition p1, final Boolean p2, final Boolean p3, final IJmlValueShape p4) throws CGException {

    try {

      ivAccess = null;
      ivStaticMod = null;
      ivFinalMod = null;
      ivShape = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      setAccess((IJmlAccessDefinition) p1);
      setStaticMod(p2);
      setFinalMod(p3);
      setShape((IJmlValueShape) p4);
    }
  }
// ***** VDMTOOLS END Name=JmlValueDefinition


// ***** VDMTOOLS START Name=JmlValueDefinition KEEP=NO
  public JmlValueDefinition (final IJmlAccessDefinition p1, final Boolean p2, final Boolean p3, final IJmlValueShape p4, final Long line, final Long column) throws CGException {

    try {

      ivAccess = null;
      ivStaticMod = null;
      ivFinalMod = null;
      ivShape = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      setAccess((IJmlAccessDefinition) p1);
      setStaticMod(p2);
      setFinalMod(p3);
      setShape((IJmlValueShape) p4);
      setPosition(line, column);
    }
  }
// ***** VDMTOOLS END Name=JmlValueDefinition


// ***** VDMTOOLS START Name=init KEEP=NO
  public void init (final HashMap data) throws CGException {

    {

      String fname = new String("access");
      Boolean cond_4 = null;
      cond_4 = new Boolean(data.containsKey(fname));
      if (cond_4.booleanValue()) 
        setAccess((IJmlAccessDefinition) data.get(fname));
    }
    {

      String fname = new String("static_mod");
      Boolean cond_13 = null;
      cond_13 = new Boolean(data.containsKey(fname));
      if (cond_13.booleanValue()) 
        setStaticMod((Boolean) data.get(fname));
    }
    {

      String fname = new String("final_mod");
      Boolean cond_22 = null;
      cond_22 = new Boolean(data.containsKey(fname));
      if (cond_22.booleanValue()) 
        setFinalMod((Boolean) data.get(fname));
    }
    {

      String fname = new String("shape");
      Boolean cond_31 = null;
      cond_31 = new Boolean(data.containsKey(fname));
      if (cond_31.booleanValue()) 
        setShape((IJmlValueShape) data.get(fname));
    }
  }
// ***** VDMTOOLS END Name=init


// ***** VDMTOOLS START Name=getAccess KEEP=NO
  public IJmlAccessDefinition getAccess () throws CGException {
    return (IJmlAccessDefinition) ivAccess;
  }
// ***** VDMTOOLS END Name=getAccess


// ***** VDMTOOLS START Name=setAccess KEEP=NO
  public void setAccess (final IJmlAccessDefinition parg) throws CGException {
    ivAccess = (IJmlAccessDefinition) UTIL.clone(parg);
  }
// ***** VDMTOOLS END Name=setAccess


// ***** VDMTOOLS START Name=getStaticMod KEEP=NO
  public Boolean getStaticMod () throws CGException {
    return ivStaticMod;
  }
// ***** VDMTOOLS END Name=getStaticMod


// ***** VDMTOOLS START Name=setStaticMod KEEP=NO
  public void setStaticMod (final Boolean parg) throws CGException {
    ivStaticMod = (Boolean) UTIL.clone(parg);
  }
// ***** VDMTOOLS END Name=setStaticMod


// ***** VDMTOOLS START Name=getFinalMod KEEP=NO
  public Boolean getFinalMod () throws CGException {
    return ivFinalMod;
  }
// ***** VDMTOOLS END Name=getFinalMod


// ***** VDMTOOLS START Name=setFinalMod KEEP=NO
  public void setFinalMod (final Boolean parg) throws CGException {
    ivFinalMod = (Boolean) UTIL.clone(parg);
  }
// ***** VDMTOOLS END Name=setFinalMod


// ***** VDMTOOLS START Name=getShape KEEP=NO
  public IJmlValueShape getShape () throws CGException {
    return (IJmlValueShape) ivShape;
  }
// ***** VDMTOOLS END Name=getShape


// ***** VDMTOOLS START Name=setShape KEEP=NO
  public void setShape (final IJmlValueShape parg) throws CGException {
    ivShape = (IJmlValueShape) UTIL.clone(parg);
  }
// ***** VDMTOOLS END Name=setShape
  
  public String toString() {
	  
	  String str = new String();
	  String access = new String();
	  String final_key = new String();
	  String static_key = new String();
	  String shape = new String();
	  
	  if(this.ivFinalMod)
		  final_key = "final ";
	  if(this.ivStaticMod)
		  static_key = "static ";
	  shape = this.ivShape.toString();
	  access = this.ivAccess.toString();

	  return access + " " + static_key + final_key + shape + ";";
  }

}
;
