//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2008-11-08 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 24-Oct-2008 08:59:25)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.potrans;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
// ***** VDMTOOLS END Name=imports



public abstract class IOmlValueDefinition extends IOmlNode {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp


// ***** VDMTOOLS START Name=vdm_init_IOmlValueDefinition KEEP=NO
  private void vdm_init_IOmlValueDefinition () throws CGException {}
// ***** VDMTOOLS END Name=vdm_init_IOmlValueDefinition


// ***** VDMTOOLS START Name=IOmlValueDefinition KEEP=NO
  public IOmlValueDefinition () throws CGException {
    vdm_init_IOmlValueDefinition();
  }
// ***** VDMTOOLS END Name=IOmlValueDefinition


// ***** VDMTOOLS START Name=getAccess KEEP=NO
  abstract public IOmlAccessDefinition getAccess () throws CGException ;
// ***** VDMTOOLS END Name=getAccess


// ***** VDMTOOLS START Name=getShape KEEP=NO
  abstract public IOmlValueShape getShape () throws CGException ;
// ***** VDMTOOLS END Name=getShape

}
;
