//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2008-11-08 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 24-Oct-2008 08:59:25)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.potrans;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
// ***** VDMTOOLS END Name=imports



public class OmlSamebaseclassExpression extends IOmlSamebaseclassExpression {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=ivLhsExpression KEEP=NO
  private IOmlExpression ivLhsExpression = null;
// ***** VDMTOOLS END Name=ivLhsExpression

// ***** VDMTOOLS START Name=ivRhsExpression KEEP=NO
  private IOmlExpression ivRhsExpression = null;
// ***** VDMTOOLS END Name=ivRhsExpression


// ***** VDMTOOLS START Name=vdm_init_OmlSamebaseclassExpression KEEP=NO
  private void vdm_init_OmlSamebaseclassExpression () throws CGException {
    try {

      ivLhsExpression = null;
      ivRhsExpression = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_OmlSamebaseclassExpression


// ***** VDMTOOLS START Name=OmlSamebaseclassExpression KEEP=NO
  public OmlSamebaseclassExpression () throws CGException {
    vdm_init_OmlSamebaseclassExpression();
  }
// ***** VDMTOOLS END Name=OmlSamebaseclassExpression


// ***** VDMTOOLS START Name=identity KEEP=NO
  public String identity () throws CGException {
    return new String("SamebaseclassExpression");
  }
// ***** VDMTOOLS END Name=identity


// ***** VDMTOOLS START Name=accept#1|IOmlVisitor KEEP=NO
  public void accept (final IOmlVisitor pVisitor) throws CGException {
    pVisitor.visitSamebaseclassExpression((IOmlSamebaseclassExpression) this);
  }
// ***** VDMTOOLS END Name=accept#1|IOmlVisitor


// ***** VDMTOOLS START Name=OmlSamebaseclassExpression#2|IOmlExpression|IOmlExpression KEEP=NO
  public OmlSamebaseclassExpression (final IOmlExpression p1, final IOmlExpression p2) throws CGException {

    vdm_init_OmlSamebaseclassExpression();
    {

      setLhsExpression((IOmlExpression) p1);
      setRhsExpression((IOmlExpression) p2);
    }
  }
// ***** VDMTOOLS END Name=OmlSamebaseclassExpression#2|IOmlExpression|IOmlExpression


// ***** VDMTOOLS START Name=init#1|HashMap KEEP=NO
  public void init (final HashMap data) throws CGException {

    {

      String fname = new String("lhs_expression");
      Boolean cond_4 = null;
      cond_4 = new Boolean(data.containsKey(fname));
      if (cond_4.booleanValue()) 
        setLhsExpression((IOmlExpression) data.get(fname));
    }
    {

      String fname = new String("rhs_expression");
      Boolean cond_13 = null;
      cond_13 = new Boolean(data.containsKey(fname));
      if (cond_13.booleanValue()) 
        setRhsExpression((IOmlExpression) data.get(fname));
    }
  }
// ***** VDMTOOLS END Name=init#1|HashMap


// ***** VDMTOOLS START Name=getLhsExpression KEEP=NO
  public IOmlExpression getLhsExpression () throws CGException {
    return (IOmlExpression) ivLhsExpression;
  }
// ***** VDMTOOLS END Name=getLhsExpression


// ***** VDMTOOLS START Name=setLhsExpression#1|IOmlExpression KEEP=NO
  public void setLhsExpression (final IOmlExpression parg) throws CGException {
    ivLhsExpression = (IOmlExpression) UTIL.clone(parg);
  }
// ***** VDMTOOLS END Name=setLhsExpression#1|IOmlExpression


// ***** VDMTOOLS START Name=getRhsExpression KEEP=NO
  public IOmlExpression getRhsExpression () throws CGException {
    return (IOmlExpression) ivRhsExpression;
  }
// ***** VDMTOOLS END Name=getRhsExpression


// ***** VDMTOOLS START Name=setRhsExpression#1|IOmlExpression KEEP=NO
  public void setRhsExpression (final IOmlExpression parg) throws CGException {
    ivRhsExpression = (IOmlExpression) UTIL.clone(parg);
  }
// ***** VDMTOOLS END Name=setRhsExpression#1|IOmlExpression

}
;
