//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2008-11-08 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 24-Oct-2008 08:59:25)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.potrans;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
// ***** VDMTOOLS END Name=imports



public class OmlThreadDefinition extends IOmlThreadDefinition {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=ivThreadSpecification KEEP=NO
  private IOmlThreadSpecification ivThreadSpecification = null;
// ***** VDMTOOLS END Name=ivThreadSpecification


// ***** VDMTOOLS START Name=vdm_init_OmlThreadDefinition KEEP=NO
  private void vdm_init_OmlThreadDefinition () throws CGException {
    try {
      ivThreadSpecification = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_OmlThreadDefinition


// ***** VDMTOOLS START Name=OmlThreadDefinition KEEP=NO
  public OmlThreadDefinition () throws CGException {
    vdm_init_OmlThreadDefinition();
  }
// ***** VDMTOOLS END Name=OmlThreadDefinition


// ***** VDMTOOLS START Name=identity KEEP=NO
  public String identity () throws CGException {
    return new String("ThreadDefinition");
  }
// ***** VDMTOOLS END Name=identity


// ***** VDMTOOLS START Name=accept#1|IOmlVisitor KEEP=NO
  public void accept (final IOmlVisitor pVisitor) throws CGException {
    pVisitor.visitThreadDefinition((IOmlThreadDefinition) this);
  }
// ***** VDMTOOLS END Name=accept#1|IOmlVisitor


// ***** VDMTOOLS START Name=OmlThreadDefinition#1|IOmlThreadSpecification KEEP=NO
  public OmlThreadDefinition (final IOmlThreadSpecification p1) throws CGException {

    vdm_init_OmlThreadDefinition();
    setThreadSpecification((IOmlThreadSpecification) p1);
  }
// ***** VDMTOOLS END Name=OmlThreadDefinition#1|IOmlThreadSpecification


// ***** VDMTOOLS START Name=init#1|HashMap KEEP=NO
  public void init (final HashMap data) throws CGException {

    String fname = new String("thread_specification");
    Boolean cond_4 = null;
    cond_4 = new Boolean(data.containsKey(fname));
    if (cond_4.booleanValue()) 
      setThreadSpecification((IOmlThreadSpecification) data.get(fname));
  }
// ***** VDMTOOLS END Name=init#1|HashMap


// ***** VDMTOOLS START Name=getThreadSpecification KEEP=NO
  public IOmlThreadSpecification getThreadSpecification () throws CGException {
    return (IOmlThreadSpecification) ivThreadSpecification;
  }
// ***** VDMTOOLS END Name=getThreadSpecification


// ***** VDMTOOLS START Name=hasThreadSpecification KEEP=NO
  public Boolean hasThreadSpecification () throws CGException {
    return new Boolean(!UTIL.equals(ivThreadSpecification, null));
  }
// ***** VDMTOOLS END Name=hasThreadSpecification


// ***** VDMTOOLS START Name=setThreadSpecification#1|IOmlThreadSpecification KEEP=NO
  public void setThreadSpecification (final IOmlThreadSpecification parg) throws CGException {
    ivThreadSpecification = (IOmlThreadSpecification) UTIL.clone(parg);
  }
// ***** VDMTOOLS END Name=setThreadSpecification#1|IOmlThreadSpecification

}
;
