//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2008-11-08 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Wed 29-Oct-2008 09:29:09)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.umltrans;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import jp.co.csk.vdm.toolbox.VDM.quotes.*;
// ***** VDMTOOLS END Name=imports



public abstract class IUmlClassType extends IUmlType {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp


// ***** VDMTOOLS START Name=vdm_init_IUmlClassType KEEP=NO
  private void vdm_init_IUmlClassType () throws CGException {}
// ***** VDMTOOLS END Name=vdm_init_IUmlClassType


// ***** VDMTOOLS START Name=IUmlClassType KEEP=NO
  public IUmlClassType () throws CGException {
    vdm_init_IUmlClassType();
  }
// ***** VDMTOOLS END Name=IUmlClassType


// ***** VDMTOOLS START Name=getId KEEP=NO
  abstract public String getId () throws CGException ;
// ***** VDMTOOLS END Name=getId


// ***** VDMTOOLS START Name=getFieldList KEEP=NO
  abstract public Vector getFieldList () throws CGException ;
// ***** VDMTOOLS END Name=getFieldList

}
;
