//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2009-02-27 by the VDM++ to JAVA Code Generator
// (v8.2b - Wed 18-Feb-2009 16:15:35)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.umltrans;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
// ***** VDMTOOLS END Name=imports



public class XmlDoc extends XmlDocument {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp


// ***** VDMTOOLS START Name=vdm_init_XmlDoc KEEP=NO
  private void vdm_init_XmlDoc () throws CGException {}
// ***** VDMTOOLS END Name=vdm_init_XmlDoc


// ***** VDMTOOLS START Name=XmlDoc KEEP=NO
  public XmlDoc () throws CGException {
    vdm_init_XmlDoc();
  }
// ***** VDMTOOLS END Name=XmlDoc


// ***** VDMTOOLS START Name=addE#1|XmlEntity KEEP=NO
  public void addE (final XmlEntity pent) throws CGException {
    addEntity((XmlEntity) pent);
  }
// ***** VDMTOOLS END Name=addE#1|XmlEntity


// ***** VDMTOOLS START Name=StartE#1|String KEEP=NO
  public void StartE (final String pname) throws CGException {
    StartEntity(pname);
  }
// ***** VDMTOOLS END Name=StartE#1|String


// ***** VDMTOOLS START Name=StopE#1|String KEEP=NO
  public void StopE (final String pname) throws CGException {
    StopEntity(pname);
  }
// ***** VDMTOOLS END Name=StopE#1|String


// ***** VDMTOOLS START Name=StartA#2|String|String KEEP=NO
  public void StartA (final String pattr, final String pval) throws CGException {
    StartAttribute(pattr, pval);
  }
// ***** VDMTOOLS END Name=StartA#2|String|String


// ***** VDMTOOLS START Name=StartD#1|String KEEP=NO
  public void StartD (final String pdata) throws CGException {
    StartData(pdata);
  }
// ***** VDMTOOLS END Name=StartD#1|String

}
;
