// this file is automatically generated by treegen. do not modify!

package org.overturetool.VDM2JavaCG.ast.java.itf;

public abstract interface IJavaSetForLoop extends IJavaForLoop
{
	public abstract String getVarName();
	public abstract IJavaExpression getSet();
	public abstract IJavaStatement getStatement();
}
