// this file is automatically generated by treegen. do not modify!

package org.overturetool.VDM2JavaCG.ast.java.itf;

// import java collection types
import java.util.*;

public abstract interface IJavaSetEnumExpression extends IJavaSetExpression
{
	public abstract List<IJavaExpression> getArgs();
}
