// this file is automatically generated by treegen. do not modify!

package org.overturetool.VDM2JavaCG.ast.java.itf;

// import java collection types
import java.util.*;

public abstract interface IJavaClassDefinitions extends IJavaSpecification
{
	public abstract List<IJavaClassDefinition> getClassList();
}
