// this file is automatically generated by treegen. do not modify!

package org.overturetool.VDM2JavaCG.ast.java.itf;

import java.util.List;

public abstract interface IJavaNode
{
	// get the parent of this node
	public abstract IJavaNode getParent();

	// set the parent of this node
	public abstract void setParent(IJavaNode pNode);

	// get the children of this node
	public abstract List<IJavaNode> getChildren();

	// visitor support
	public abstract void accept(IJavaVisitor pVisitor);

	// the identity function
	public abstract String identify();
}
