// this file is automatically generated by treegen. do not modify!

package org.overturetool.VDM2JavaCG.ast.java.itf;

public abstract interface IJavaBooleanLiteral extends IJavaLiteral
{
	public abstract Boolean getVal();
}
