package org.overture.tools.treegen;
public interface TreeParserTokens {
public final static short CLASS=257;
public final static short IS=258;
public final static short SUBCLASS=259;
public final static short OF=260;
public final static short END=261;
public final static short VALUES=262;
public final static short DCOLON=263;
public final static short SCOLON=264;
public final static short COLON=265;
public final static short ASSIGN=266;
public final static short SEQ=267;
public final static short SET=268;
public final static short MAP=269;
public final static short TO=270;
public final static short BAR=271;
public final static short IDENT=272;
public final static short EQ=273;
public final static short LB=274;
public final static short RB=275;
public final static short LP=276;
public final static short RP=277;
public final static short QUOTE=278;
public final static short STRING=279;
public final static short MK_TOKEN=280;
public final static short TYPES=281;
public final static short BOOLEAN=282;
public final static short INSTANCE=283;
public final static short VARIABLES=284;
}
