//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2009-03-29 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 24-Oct-2008 08:59:25)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=YES
package org.overturetool.potrans;
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

import java.util.HashSet;
import java.util.Iterator;
import java.util.Vector;

import jp.co.csk.vdm.toolbox.VDM.CGException;
import jp.co.csk.vdm.toolbox.VDM.UTIL;

import org.overturetool.potrans.quotes.type;

// ***** VDMTOOLS END Name=imports

public class HolBracketedType extends HolType {

	// ***** VDMTOOLS START Name=vdmComp KEEP=NO
	static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
	// ***** VDMTOOLS END Name=vdmComp

	// ***** VDMTOOLS START Name=val KEEP=NO
	private volatile HolType val = null;

	// ***** VDMTOOLS END Name=val

	// ***** VDMTOOLS START Name=vdm_init_HolBracketedType KEEP=NO
	private void vdm_init_HolBracketedType() throws CGException {
	}

	// ***** VDMTOOLS END Name=vdm_init_HolBracketedType

	// ***** VDMTOOLS START Name=HolBracketedType KEEP=NO
	public HolBracketedType() throws CGException {
		vdm_init_HolBracketedType();
	}

	// ***** VDMTOOLS END Name=HolBracketedType

	// ***** VDMTOOLS START Name=HolBracketedType#1|HolType KEEP=NO
	public HolBracketedType(final HolType newVal) throws CGException {

		vdm_init_HolBracketedType();
		val = (HolType) UTIL.clone(newVal);
	}

	// ***** VDMTOOLS END Name=HolBracketedType#1|HolType

	// ***** VDMTOOLS START Name=setTypeInformation#1|HolTypeDescription
	// KEEP=YES
	public void setTypeInformation(final HolTypeDescription typeInfo)
			throws CGException {
		val.setTypeInformation((HolTypeDescription) typeInfo);
	}

	// ***** VDMTOOLS END Name=setTypeInformation#1|HolTypeDescription

	// ***** VDMTOOLS START Name=requires KEEP=NO
	public HashSet requires() throws CGException {
		HashSet rexpr_1 = new HashSet();
		rexpr_1 = val.requires();
		return rexpr_1;
	}

	// ***** VDMTOOLS END Name=requires

	// ***** VDMTOOLS START Name=print#1|Object KEEP=NO
	public String print(final Object specType) throws CGException {

		if (!this.pre_print(specType).booleanValue())
			UTIL.RunTime("Run-Time Error:Precondition failure in print");

		String rexpr_2 = null;
		Vector unArg_3 = null;
		unArg_3 = new Vector();
		unArg_3.add(new String(" ("));
		String e_seq_5 = null;
		e_seq_5 = val.print(new type());
		unArg_3.add(e_seq_5);
		unArg_3.add(new String(") "));
		String rdcseq_8 = new String();
		for (Iterator enm_11 = unArg_3.iterator(); enm_11.hasNext();) {

			String e_9 = UTIL.ConvertToString(enm_11.next());
			rdcseq_8 = rdcseq_8.concat(e_9);
		}
		rexpr_2 = rdcseq_8;
		return rexpr_2;
	
	}

	// ***** VDMTOOLS END Name=print#1|Object

	// ***** VDMTOOLS START Name=pre_print#1|Object KEEP=NO
	public Boolean pre_print(final Object specType) throws CGException {
		return new Boolean(UTIL.equals(specType, new type()));
	}
	// ***** VDMTOOLS END Name=pre_print#1|Object

};
