

//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2009-08-09 by the VDM++ to JAVA Code Generator
// (v8.2.1b - Wed 15-Jul-2009 14:09:22)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.test1;

// ***** VDMTOOLS END Name=package
// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import jp.co.csk.vdm.toolbox.VDM.quotes.*;
import org.overturetool.test1.*;
// ***** VDMTOOLS END Name=imports



public class simpleClass {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp


// ***** VDMTOOLS START Name=vdm_init_simpleClass KEEP=NO
  private void vdm_init_simpleClass () throws CGException {}
// ***** VDMTOOLS END Name=vdm_init_simpleClass


// ***** VDMTOOLS START Name=simpleClass KEEP=NO
  public simpleClass () throws CGException {
    vdm_init_simpleClass();
  }
// ***** VDMTOOLS END Name=simpleClass

}
;