//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2008-11-08 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 24-Oct-2008 08:59:25)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.potrans;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
// ***** VDMTOOLS END Name=imports



public abstract class IOmlSimpleType extends IOmlTypeShape {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp


// ***** VDMTOOLS START Name=vdm_init_IOmlSimpleType KEEP=NO
  private void vdm_init_IOmlSimpleType () throws CGException {}
// ***** VDMTOOLS END Name=vdm_init_IOmlSimpleType


// ***** VDMTOOLS START Name=IOmlSimpleType KEEP=NO
  public IOmlSimpleType () throws CGException {
    vdm_init_IOmlSimpleType();
  }
// ***** VDMTOOLS END Name=IOmlSimpleType


// ***** VDMTOOLS START Name=getIdentifier KEEP=NO
  abstract public String getIdentifier () throws CGException ;
// ***** VDMTOOLS END Name=getIdentifier


// ***** VDMTOOLS START Name=getType KEEP=NO
  abstract public IOmlType getType () throws CGException ;
// ***** VDMTOOLS END Name=getType


// ***** VDMTOOLS START Name=getInvariant KEEP=NO
  abstract public IOmlInvariant getInvariant () throws CGException ;
// ***** VDMTOOLS END Name=getInvariant


// ***** VDMTOOLS START Name=hasInvariant KEEP=NO
  abstract public Boolean hasInvariant () throws CGException ;
// ***** VDMTOOLS END Name=hasInvariant

}
;
