//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2008-11-08 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 24-Oct-2008 08:59:25)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.potrans;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
// ***** VDMTOOLS END Name=imports



public abstract class IOmlObjectFieldReference extends IOmlObjectDesignator {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp


// ***** VDMTOOLS START Name=vdm_init_IOmlObjectFieldReference KEEP=NO
  private void vdm_init_IOmlObjectFieldReference () throws CGException {}
// ***** VDMTOOLS END Name=vdm_init_IOmlObjectFieldReference


// ***** VDMTOOLS START Name=IOmlObjectFieldReference KEEP=NO
  public IOmlObjectFieldReference () throws CGException {
    vdm_init_IOmlObjectFieldReference();
  }
// ***** VDMTOOLS END Name=IOmlObjectFieldReference


// ***** VDMTOOLS START Name=getObjectDesignator KEEP=NO
  abstract public IOmlObjectDesignator getObjectDesignator () throws CGException ;
// ***** VDMTOOLS END Name=getObjectDesignator


// ***** VDMTOOLS START Name=getName KEEP=NO
  abstract public IOmlName getName () throws CGException ;
// ***** VDMTOOLS END Name=getName

}
;
