//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2008-11-08 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 24-Oct-2008 08:59:25)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.potrans;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
// ***** VDMTOOLS END Name=imports



public abstract class IOmlFieldReference extends IOmlStateDesignator {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp


// ***** VDMTOOLS START Name=vdm_init_IOmlFieldReference KEEP=NO
  private void vdm_init_IOmlFieldReference () throws CGException {}
// ***** VDMTOOLS END Name=vdm_init_IOmlFieldReference


// ***** VDMTOOLS START Name=IOmlFieldReference KEEP=NO
  public IOmlFieldReference () throws CGException {
    vdm_init_IOmlFieldReference();
  }
// ***** VDMTOOLS END Name=IOmlFieldReference


// ***** VDMTOOLS START Name=getStateDesignator KEEP=NO
  abstract public IOmlStateDesignator getStateDesignator () throws CGException ;
// ***** VDMTOOLS END Name=getStateDesignator


// ***** VDMTOOLS START Name=getIdentifier KEEP=NO
  abstract public String getIdentifier () throws CGException ;
// ***** VDMTOOLS END Name=getIdentifier

}
;
