//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2008-11-08 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 24-Oct-2008 08:59:25)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.potrans;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
// ***** VDMTOOLS END Name=imports



public class OmlQuoteType extends IOmlQuoteType {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=ivQuoteLiteral KEEP=NO
  private IOmlQuoteLiteral ivQuoteLiteral = null;
// ***** VDMTOOLS END Name=ivQuoteLiteral


// ***** VDMTOOLS START Name=vdm_init_OmlQuoteType KEEP=NO
  private void vdm_init_OmlQuoteType () throws CGException {
    try {
      ivQuoteLiteral = null;
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_OmlQuoteType


// ***** VDMTOOLS START Name=OmlQuoteType KEEP=NO
  public OmlQuoteType () throws CGException {
    vdm_init_OmlQuoteType();
  }
// ***** VDMTOOLS END Name=OmlQuoteType


// ***** VDMTOOLS START Name=identity KEEP=NO
  public String identity () throws CGException {
    return new String("QuoteType");
  }
// ***** VDMTOOLS END Name=identity


// ***** VDMTOOLS START Name=accept#1|IOmlVisitor KEEP=NO
  public void accept (final IOmlVisitor pVisitor) throws CGException {
    pVisitor.visitQuoteType((IOmlQuoteType) this);
  }
// ***** VDMTOOLS END Name=accept#1|IOmlVisitor


// ***** VDMTOOLS START Name=OmlQuoteType#1|IOmlQuoteLiteral KEEP=NO
  public OmlQuoteType (final IOmlQuoteLiteral p1) throws CGException {

    vdm_init_OmlQuoteType();
    setQuoteLiteral((IOmlQuoteLiteral) p1);
  }
// ***** VDMTOOLS END Name=OmlQuoteType#1|IOmlQuoteLiteral


// ***** VDMTOOLS START Name=init#1|HashMap KEEP=NO
  public void init (final HashMap data) throws CGException {

    String fname = new String("quote_literal");
    Boolean cond_4 = null;
    cond_4 = new Boolean(data.containsKey(fname));
    if (cond_4.booleanValue()) 
      setQuoteLiteral((IOmlQuoteLiteral) data.get(fname));
  }
// ***** VDMTOOLS END Name=init#1|HashMap


// ***** VDMTOOLS START Name=getQuoteLiteral KEEP=NO
  public IOmlQuoteLiteral getQuoteLiteral () throws CGException {
    return (IOmlQuoteLiteral) ivQuoteLiteral;
  }
// ***** VDMTOOLS END Name=getQuoteLiteral


// ***** VDMTOOLS START Name=setQuoteLiteral#1|IOmlQuoteLiteral KEEP=NO
  public void setQuoteLiteral (final IOmlQuoteLiteral parg) throws CGException {
    ivQuoteLiteral = (IOmlQuoteLiteral) UTIL.clone(parg);
  }
// ***** VDMTOOLS END Name=setQuoteLiteral#1|IOmlQuoteLiteral

}
;
