//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2009-11-27 by the VDM++ to JAVA Code Generator
// (v8.2 - Fri 29-May-2009 11:13:11)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.umltrans.vdm2uml;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
// ***** VDMTOOLS END Name=imports

import org.overturetool.ast.itf.IOmlPartialFunctionType;



public class external_Vdm2UmlType {

// ***** VDMTOOLS START Name=parent KEEP=NO
  Vdm2UmlType parent = null;
// ***** VDMTOOLS END Name=parent


// ***** VDMTOOLS START Name=external_Vdm2UmlType#1|Vdm2UmlType KEEP=NO
  public external_Vdm2UmlType (Vdm2UmlType parentVdm2UmlType) {
    parent = parentVdm2UmlType;
  }
// ***** VDMTOOLS END Name=external_Vdm2UmlType#1|Vdm2UmlType


// ***** VDMTOOLS START Name=external_Vdm2UmlType KEEP=NO
  public external_Vdm2UmlType () {}
// ***** VDMTOOLS END Name=external_Vdm2UmlType


// ***** VDMTOOLS START Name=impl_GenFnType#2|Vector|Vector KEEP=NO
  public IOmlPartialFunctionType impl_GenFnType (final Vector pattype_ul, final Vector restype_ul) throws CGException {

    UTIL.RunTime("Run-Time Error:Implicit Function GenFnType has been called");
    return null;//new IOmlPartialFunctionType();
  }
// ***** VDMTOOLS END Name=impl_GenFnType#2|Vector|Vector

}
;
