//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2009-08-09 by the VDM++ to JAVA Code Generator
// (v8.2.1b - Wed 15-Jul-2009 14:09:22)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.api.xml;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
// ***** VDMTOOLS END Name=imports



public class XmlFactory {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp


// ***** VDMTOOLS START Name=vdm_init_XmlFactory KEEP=NO
  private void vdm_init_XmlFactory () throws CGException {}
// ***** VDMTOOLS END Name=vdm_init_XmlFactory


// ***** VDMTOOLS START Name=XmlFactory KEEP=NO
  public XmlFactory () throws CGException {
    vdm_init_XmlFactory();
  }
// ***** VDMTOOLS END Name=XmlFactory


// ***** VDMTOOLS START Name=readFromFile#1|String KEEP=NO
  static public XmlDocument readFromFile (final String pfn) throws CGException {

    XmlDocument pnxd = new XmlDocument();
    pnxd.parse(pfn);
    return (XmlDocument) pnxd;
  }
// ***** VDMTOOLS END Name=readFromFile#1|String


// ***** VDMTOOLS START Name=writeToFile#2|String|XmlDocument KEEP=NO
  static public void writeToFile (final String pfn, final XmlDocument pxd) throws CGException {}
// ***** VDMTOOLS END Name=writeToFile#2|String|XmlDocument

}
;
