package org.overture.pog.tests;

/**
 * @author rala
 */
enum ThirdPartyTests implements AbstractTests
{
	applyexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-01.vdm"), applyexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-02.vdm"), applyexpr_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-03.vdm"), applyexpr_04$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-04.vdm"), applyexpr_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-05.vdm"), applyexpr_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-06.vdm"), applyexpr_07$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-07.vdm"), applyexpr_08$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-08.vdm"), applyexpr_09$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-09.vdm"), applyexpr_10$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-10.vdm"), applyexpr_14$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-14.vdm"), applyexpr_16$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-16.vdm"), applyexpr_18$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-18.vdm"), applyexpr_19$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-19.vdm"), applyexpr_23$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/applyexpr/applyexpr-23.vdm"), and_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/and/and-01.vdm"), eq_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/eq/eq-01.vdm"), equiv_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/equiv/equiv-01.vdm"), imply_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/imply/imply-01.vdm"), inset_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/inset/inset-03.vdm"), intdiv_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/intdiv/intdiv-01.vdm"), intdiv_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/intdiv/intdiv-02.vdm"), intdiv_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/intdiv/intdiv-03.vdm"), mapdomrestby_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/mapdomrestby/mapdomrestby-06.vdm"), mapmerge_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/mapmerge/mapmerge-01.vdm"), maprngrestby_04$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/maprngrestby/maprngrestby-04.vdm"), maprngrestby_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/maprngrestby/maprngrestby-06.vdm"), maprngrestto_04$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/maprngrestto/maprngrestto-04.vdm"), maprngrestto_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/maprngrestto/maprngrestto-06.vdm"), ne_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/ne/ne-01.vdm"), ne_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/ne/ne-02.vdm"), ne_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/ne/ne-03.vdm"), notinset_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/notinset/notinset-01.vdm"), notinset_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/notinset/notinset-03.vdm"), numdiv_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numdiv/numdiv-01.vdm"), numdiv_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numdiv/numdiv-02.vdm"), numdiv_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numdiv/numdiv-03.vdm"), numge_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numge/numge-01.vdm"), numge_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numge/numge-02.vdm"), numge_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numge/numge-03.vdm"), numgt_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numgt/numgt-01.vdm"), numgt_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numgt/numgt-02.vdm"), numgt_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numgt/numgt-03.vdm"), numle_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numle/numle-01.vdm"), numle_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numle/numle-02.vdm"), numle_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numle/numle-03.vdm"), numlt_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numlt/numlt-01.vdm"), numlt_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numlt/numlt-02.vdm"), numlt_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numlt/numlt-03.vdm"), numminus_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numminus/numminus-02.vdm"), numminus_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numminus/numminus-03.vdm"), nummod_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/nummod/nummod-01.vdm"), nummod_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/nummod/nummod-02.vdm"), nummod_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/nummod/nummod-03.vdm"), nummult_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/nummult/nummult-01.vdm"), nummult_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/nummult/nummult-02.vdm"), nummult_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/nummult/nummult-03.vdm"), numplus_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numplus/numplus-02.vdm"), numplus_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numplus/numplus-03.vdm"), numplus_07$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numplus/numplus-07.vdm"), numrem_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numrem/numrem-01.vdm"), numrem_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numrem/numrem-02.vdm"), numrem_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/numrem/numrem-03.vdm"), or_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/or/or-01.vdm"), propersubset_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/propersubset/propersubset-01.vdm"), seqconc_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/seqconc/seqconc-01.vdm"), setintersect_07$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/setintersect/setintersect-07.vdm"), setintersect_08$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/setintersect/setintersect-08.vdm"), setintersect_09$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/setintersect/setintersect-09.vdm"), setunion_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/setunion/setunion-01.vdm"), setunion_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/setunion/setunion-06.vdm"), subset_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/binaryexpr/subset/subset-01.vdm"), casesexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/casesexpr/casesexpr-01.vdm"), casesexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/casesexpr/casesexpr-02.vdm"), casesexpr_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/casesexpr/casesexpr-03.vdm"), compose_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/compose/compose-01.vdm"), compose_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/compose/compose-02.vdm"), compose_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/compose/compose-03.vdm"), compose_04$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/compose/compose-04.vdm"), compose_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/compose/compose-05.vdm"), compose_07$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/compose/compose-07.vdm"), compose_08$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/compose/compose-08.vdm"), defexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/defexpr/defexpr-01.vdm"), defexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/defexpr/defexpr-02.vdm"), defexpr_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/defexpr/defexpr-03.vdm"), fcttypeinstexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/fcttypeinstexpr/fcttypeinstexpr-01.vdm"), ifexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/ifexpr/ifexpr-01.vdm"), ifexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/ifexpr/ifexpr-02.vdm"), ifexpr_04$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/ifexpr/ifexpr-04.vdm"), ifexpr_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/ifexpr/ifexpr-05.vdm"), iotaexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/iotaexpr/iotaexpr-02.vdm"), iotaexpr_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/iotaexpr/iotaexpr-03.vdm"), isexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/isexpr/isexpr-01.vdm"), isexpr_04$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/isexpr/isexpr-04.vdm"), isexpr_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/isexpr/isexpr-06.vdm"), isexpr_07$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/isexpr/isexpr-07.vdm"), isexpr_09$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/isexpr/isexpr-09.vdm"), isexpr_10$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/isexpr/isexpr-10.vdm"), isexpr_12$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/isexpr/isexpr-12.vdm"), lambdaexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/lambdaexpr/lambdaexpr-01.vdm"), lambdaexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/lambdaexpr/lambdaexpr-02.vdm"), lambdaexpr_04$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/lambdaexpr/lambdaexpr-04.vdm"), letbestexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/letbestexpr/letbestexpr-01.vdm"), letbestexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/letbestexpr/letbestexpr-02.vdm"), letbestexpr_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/letbestexpr/letbestexpr-03.vdm"), letbestexpr_04$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/letbestexpr/letbestexpr-04.vdm"), letbestexpr_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/letbestexpr/letbestexpr-05.vdm"), letbestexpr_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/letbestexpr/letbestexpr-06.vdm"), letbestexpr_07$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/letbestexpr/letbestexpr-07.vdm"), letbestexpr_09$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/letbestexpr/letbestexpr-09.vdm"), letbestexpr_11$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/letbestexpr/letbestexpr-11.vdm"), letbestexpr_12$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/letbestexpr/letbestexpr-12.vdm"), letexpr_24$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/letexpr/letexpr-24.vdm"), literal_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/literal/literal-01.vdm"), literal_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/literal/literal-02.vdm"), mapcomprehensionexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/mapcomprehensionexpr/mapcomprehensionexpr-01.vdm"), mapcomprehensionexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/mapcomprehensionexpr/mapcomprehensionexpr-02.vdm"), mapcomprehensionexpr_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/mapcomprehensionexpr/mapcomprehensionexpr-05.vdm"), mapenumerationexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/mapenumerationexpr/mapenumerationexpr-01.vdm"), mapenumerationexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/mapenumerationexpr/mapenumerationexpr-02.vdm"), mapinverseexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/mapinverseexpr/mapinverseexpr-01.vdm"), mapinverseexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/mapinverseexpr/mapinverseexpr-02.vdm"), mapinverseexpr_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/mapinverseexpr/mapinverseexpr-03.vdm"), numexp_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/numexp/numexp-01.vdm"), numexp_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/numexp/numexp-02.vdm"), numexp_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/numexp/numexp-03.vdm"), numexp_04$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/numexp/numexp-04.vdm"), numexp_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/numexp/numexp-05.vdm"), numexp_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/numexp/numexp-06.vdm"), numexp_07$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/numexp/numexp-07.vdm"), numexp_08$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/numexp/numexp-08.vdm"), numexp_09$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/numexp/numexp-09.vdm"), numexp_10$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/numexp/numexp-10.vdm"), numexp_11$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/numexp/numexp-11.vdm"), numexp_12$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/numexp/numexp-12.vdm"), preconditionapplyexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/preconditionapplyexpr/preconditionapplyexpr-01.vdm"), quantexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/quantexpr/quantexpr-01.vdm"), quantexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/quantexpr/quantexpr-02.vdm"), quantexpr_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/quantexpr/quantexpr-05.vdm"), quantexpr_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/quantexpr/quantexpr-06.vdm"), recordconstructorexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/recordconstructorexpr/recordconstructorexpr-01.vdm"), recordconstructorexpr_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/recordconstructorexpr/recordconstructorexpr-05.vdm"), recordmodifierexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/recordmodifierexpr/recordmodifierexpr-01.vdm"), recordmodifierexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/recordmodifierexpr/recordmodifierexpr-02.vdm"), recordmodifierexpr_04$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/recordmodifierexpr/recordmodifierexpr-04.vdm"), recordmodifierexpr_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/recordmodifierexpr/recordmodifierexpr-05.vdm"), recordmodifierexpr_07$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/recordmodifierexpr/recordmodifierexpr-07.vdm"), recordmodifierexpr_08$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/recordmodifierexpr/recordmodifierexpr-08.vdm"), recordmodifierexpr_09$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/recordmodifierexpr/recordmodifierexpr-09.vdm"), seqenumerationexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/seqenumerationexpr/seqenumerationexpr-01.vdm"), seqenumerationexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/seqenumerationexpr/seqenumerationexpr-02.vdm"), seqenumerationexpr_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/seqenumerationexpr/seqenumerationexpr-03.vdm"), seqmodifymapoverrideexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/seqmodifymapoverrideexpr/seqmodifymapoverrideexpr-01.vdm"), seqmodifymapoverrideexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/seqmodifymapoverrideexpr/seqmodifymapoverrideexpr-02.vdm"), seqmodifymapoverrideexpr_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/seqmodifymapoverrideexpr/seqmodifymapoverrideexpr-03.vdm"), seqmodifymapoverrideexpr_08$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/seqmodifymapoverrideexpr/seqmodifymapoverrideexpr-08.vdm"), seqmodifymapoverrideexpr_11$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/seqmodifymapoverrideexpr/seqmodifymapoverrideexpr-11.vdm"), seqmodifymapoverrideexpr_15$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/seqmodifymapoverrideexpr/seqmodifymapoverrideexpr-15.vdm"), seqmodifymapoverrideexpr_17$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/seqmodifymapoverrideexpr/seqmodifymapoverrideexpr-17.vdm"), seqmodifymapoverrideexpr_18$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/seqmodifymapoverrideexpr/seqmodifymapoverrideexpr-18.vdm"), setcomprehensionexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/setcomprehensionexpr/setcomprehensionexpr-01.vdm"), setcomprehensionexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/setcomprehensionexpr/setcomprehensionexpr-02.vdm"), setcomprehensionexpr_04$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/setcomprehensionexpr/setcomprehensionexpr-04.vdm"), setcomprehensionexpr_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/setcomprehensionexpr/setcomprehensionexpr-05.vdm"), setenumerationexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/setenumerationexpr/setenumerationexpr-01.vdm"), setenumerationexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/setenumerationexpr/setenumerationexpr-02.vdm"), setrangeexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/setrangeexpr/setrangeexpr-01.vdm"), setrangeexpr_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/setrangeexpr/setrangeexpr-03.vdm"), subsequenceexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/subsequenceexpr/subsequenceexpr-01.vdm"), tokenconstructorexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/tokenconstructorexpr/tokenconstructorexpr-01.vdm"), tupleconstructorexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/tupleconstructorexpr/tupleconstructorexpr-01.vdm"), tupleconstructorexpr_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/tupleconstructorexpr/tupleconstructorexpr-02.vdm"), tupleselectexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/tupleselectexpr/tupleselectexpr-01.vdm"), tupleselectexpr_04$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/tupleselectexpr/tupleselectexpr-04.vdm"), tupleselectexpr_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/tupleselectexpr/tupleselectexpr-05.vdm"), tupleselectexpr_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/tupleselectexpr/tupleselectexpr-06.vdm"), floor_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/floor/floor-01.vdm"), mapdistrmerge_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/mapdistrmerge/mapdistrmerge-01.vdm"), mapdom_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/mapdom/mapdom-01.vdm"), mapdom_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/mapdom/mapdom-02.vdm"), mapdom_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/mapdom/mapdom-05.vdm"), mapdom_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/mapdom/mapdom-06.vdm"), maprng_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/maprng/maprng-01.vdm"), maprng_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/maprng/maprng-02.vdm"), not_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/not/not-01.vdm"), numabs_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/numabs/numabs-01.vdm"), numminus_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/numminus/numminus-01.vdm"), numminus_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/numminus/numminus-06.vdm"), numplus_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/numplus/numplus-01.vdm"), seqdistrconc_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/seqdistrconc/seqdistrconc-01.vdm"), seqelems_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/seqelems/seqelems-01.vdm"), seqelems_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/seqelems/seqelems-02.vdm"), seqhead_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/seqhead/seqhead-01.vdm"), seqindices_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/seqindices/seqindices-01.vdm"), seqlen_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/seqlen/seqlen-01.vdm"), seqlen_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/seqlen/seqlen-03.vdm"), seqtail_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/seqtail/seqtail-01.vdm"), setcard_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/setcard/setcard-01.vdm"), setdistrintersect_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/setdistrintersect/setdistrintersect-01.vdm"), setdistrintersect_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/setdistrintersect/setdistrintersect-02.vdm"), setdistrintersect_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/setdistrintersect/setdistrintersect-03.vdm"), setdistrintersect_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/setdistrintersect/setdistrintersect-05.vdm"), setdistrintersect_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/setdistrintersect/setdistrintersect-06.vdm"), setdistrintersect_07$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/setdistrintersect/setdistrintersect-07.vdm"), setdistrintersect_08$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/setdistrintersect/setdistrintersect-08.vdm"), setdistrunion_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/setdistrunion/setdistrunion-01.vdm"), setdistrunion_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/setdistrunion/setdistrunion-02.vdm"), setdistrunion_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/setdistrunion/setdistrunion-06.vdm"), setpower_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/setpower/setpower-01.vdm"), setpower_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/unaryexpr/setpower/setpower-02.vdm"), undefinedexpr_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/expr/undefinedexpr/undefinedexpr-01.vdm"), basic_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-01.vdm"), basic_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-02.vdm"), basic_03$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-03.vdm"), basic_04$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-04.vdm"), basic_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-05.vdm"), basic_10$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-10.vdm"), basic_11$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-11.vdm"), basic_12$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-12.vdm"), basic_13$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-13.vdm"), basic_14$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-14.vdm"), basic_19$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-19.vdm"), basic_20$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-20.vdm"), basic_21$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-21.vdm"), basic_22$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-22.vdm"), basic_23$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-23.vdm"), basic_28$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-28.vdm"), basic_29$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-29.vdm"), basic_30$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-30.vdm"), basic_31$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-31.vdm"), basic_32$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-32.vdm"), basic_37$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-37.vdm"), basic_38$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-38.vdm"), basic_39$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-39.vdm"), basic_40$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-40.vdm"), basic_41$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-41.vdm"), basic_51$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-51.vdm"), basic_61$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-61.vdm"), basic_71$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-71.vdm"), basic_81$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/basic/basic-81.vdm"), seq_01$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/seq/seq-01.vdm"), seq_02$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/seq/seq-02.vdm"), seq_05$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/seq/seq-05.vdm"), seq_06$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/seq/seq-06.vdm"), seq_11$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/seq/seq-11.vdm"), seq_12$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/seq/seq-12.vdm"), seq_15$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/seq/seq-15.vdm"), seq_16$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/seq/seq-16.vdm"), subtype_001$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-001.vdm"), subtype_002$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-002.vdm"), subtype_010$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-010.vdm"), subtype_014$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-014.vdm"), subtype_022$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-022.vdm"), subtype_026$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-026.vdm"), subtype_027$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-027.vdm"), subtype_034$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-034.vdm"), subtype_040$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-040.vdm"), subtype_044$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-044.vdm"), subtype_045$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-045.vdm"), subtype_053$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-053.vdm"), subtype_066$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-066.vdm"), subtype_078$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-078.vdm"), subtype_079$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-079.vdm"), subtype_092$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-092.vdm"), subtype_093$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-093.vdm"), subtype_104$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-104.vdm"), subtype_105$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-105.vdm"), subtype_109$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-109.vdm"), subtype_111$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-111.vdm"), subtype_118$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-118.vdm"), subtype_131$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-131.vdm"), subtype_132$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-132.vdm"), subtype_144$vdm(
			"thirdpartytests//pog/exprtest/CORE/iscompatible/subtype/subtype-144.vdm"), alarm$vdm(
			"thirdpartytests//pog/fulltest/CORE/examples/alarm.vdm"), autopilot$vdm(
			"thirdpartytests//pog/fulltest/CORE/examples/autopilot.vdm"), db_linecond41$vdm(
			"thirdpartytests//pog/fulltest/CORE/examples/db-linecond41.vdm"), memory$vdm(
			"thirdpartytests//pog/fulltest/CORE/examples/memory.vdm"), safer$vdm(
			"thirdpartytests//pog/fulltest/CORE/examples/safer.vdm"), tracker$vdm(
			"thirdpartytests//pog/fulltest/CORE/examples/tracker.vdm"), extexplfndef_01$vdm(
			"thirdpartytests//pog/fulltest/CORE/extexplfndef/extexplfndef-01.vdm"), fundefsl_01$vdm(
			"thirdpartytests//pog/fulltest/CORE/fundefsl/fundefsl-01.vdm"), fundefsl_02$vdm(
			"thirdpartytests//pog/fulltest/CORE/fundefsl/fundefsl-02.vdm"), fundefsl_03$vdm(
			"thirdpartytests//pog/fulltest/CORE/fundefsl/fundefsl-03.vdm"), isnotyetspec$vdm(
			"thirdpartytests//pog/fulltest/CORE/isnotyetspec/isnotyetspec.vdm"), misc$vdm(
			"thirdpartytests//pog/fulltest/CORE/misc/misc.vdm"), recfun_01$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-01.vdm"), recfun_02$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-02.vdm"), recfun_04$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-04.vdm"), recfun_07$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-07.vdm"), recfun_09$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-09.vdm"), recfun_10$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-10.vdm"), recfun_11$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-11.vdm"), recfun_12$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-12.vdm"), recfun_14$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-14.vdm"), recfun_17$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-17.vdm"), recfun_19$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-19.vdm"), recfun_20$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-20.vdm"), recfun_21$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-21.vdm"), recfun_22$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-22.vdm"), recfun_24$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-24.vdm"), recfun_25$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-25.vdm"), recfun_26$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-26.vdm"), recfun_27$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-27.vdm"), recfun_28$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-28.vdm"), recfun_29$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-29.vdm"), recfun_34$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-34.vdm"), recfun_35$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-35.vdm"), recfun_36$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-36.vdm"), recfun_40$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-40.vdm"), recfun_41$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-41.vdm"), recfun_42$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-42.vdm"), recfun_44$vdm(
			"thirdpartytests//pog/fulltest/CORE/recfun/recfun-44.vdm"), blockstmt_01$vdm(
			"thirdpartytests//pog/fulltest/CORE/stmt/blockstmt/blockstmt-01.vdm"), casesstmt_01$vdm(
			"thirdpartytests//pog/fulltest/CORE/stmt/casesstmt/casesstmt-01.vdm"), casesstmt_02$vdm(
			"thirdpartytests//pog/fulltest/CORE/stmt/casesstmt/casesstmt-02.vdm"), casesstmt_06$vdm(
			"thirdpartytests//pog/fulltest/CORE/stmt/casesstmt/casesstmt-06.vdm"), casesstmt_08$vdm(
			"thirdpartytests//pog/fulltest/CORE/stmt/casesstmt/casesstmt-08.vdm"), error$vdm(
			"thirdpartytests//pog/fulltest/CORE/stmt/error.vdm"), identstmt$vdm(
			"thirdpartytests//pog/fulltest/CORE/stmt/identstmt/identstmt.vdm"), if_01$vdm(
			"thirdpartytests//pog/fulltest/CORE/stmt/ifstmt/if-01.vdm"), if_02$vdm(
			"thirdpartytests//pog/fulltest/CORE/stmt/ifstmt/if-02.vdm"), indexforloopstmt_02$vdm(
			"thirdpartytests//pog/fulltest/CORE/stmt/indexforloopstmt/indexforloopstmt-02.vdm"), letbestmt_01$vdm(
			"thirdpartytests//pog/fulltest/CORE/stmt/letbestmt/letbestmt-01.vdm"), seqforloopstmt_01$vdm(
			"thirdpartytests//pog/fulltest/CORE/stmt/seqforloopstmt/seqforloopstmt-01.vdm"), type_01$vdm(
			"thirdpartytests//pog/fulltest/CORE/type/type-01.vdm"), type_02$vdm(
			"thirdpartytests//pog/fulltest/CORE/type/type-02.vdm"), type_03$vdm(
			"thirdpartytests//pog/fulltest/CORE/type/type-03.vdm"), type_04$vdm(
			"thirdpartytests//pog/fulltest/CORE/type/type-04.vdm"), type_05$vdm(
			"thirdpartytests//pog/fulltest/CORE/type/type-05.vdm"), type_06$vdm(
			"thirdpartytests//pog/fulltest/CORE/type/type-06.vdm"), value_01$vdm(
			"thirdpartytests//pog/fulltest/CORE/value/value-01.vdm"), modules05$vdm(
			"thirdpartytests//pog/fulltest/SL/modules05/modules05.vdm"), modules08$vdm(
			"thirdpartytests//pog/fulltest/SL/modules08/modules08.vdm"), modules11$vdm(
			"thirdpartytests//pog/fulltest/SL/modules11/modules11.vdm"), modules12$vdm(
			"thirdpartytests//pog/fulltest/SL/modules12/modules12.vdm"), modules13$vdm(
			"thirdpartytests//pog/fulltest/SL/modules13/modules13.vdm"), modules21$vdm(
			"thirdpartytests//pog/fulltest/SL/modules21/modules21.vdm"), blockstmt$vdm(
			"thirdpartytests//pog/fulltest/SL/stmtsl/blockstmt/blockstmt.vdm"), ;
	private String filePath;

	ThirdPartyTests(String fp)
	{
		this.filePath = fp;
	}

	public String getFolder()
	{
		return this.filePath;
	}

	public String toString()
	{
		return this.filePath;
	}

};
