package org.overture.pog.tests;

enum Thirdpartytests_pp implements AbstractTests
{
	apply_01$vpp("thirdpartytests/pp/pog/exprtest/PP/exprpp/apply/apply-01.vpp"), apply_02$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/apply/apply-02.vpp"), apply_03$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/apply/apply-03.vpp"), apply_04$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/apply/apply-04.vpp"), apply_05$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/apply/apply-05.vpp"), apply_06$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/apply/apply-06.vpp"), baseaccess1_01$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-01.vpp"), baseaccess1_02$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-02.vpp"), baseaccess1_03$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-03.vpp"), baseaccess1_04$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-04.vpp"), baseaccess1_05$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-05.vpp"), baseaccess1_06$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-06.vpp"), baseaccess1_07$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-07.vpp"), baseaccess1_08$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-08.vpp"), baseaccess1_09$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-09.vpp"), baseaccess1_10$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-10.vpp"), baseaccess1_11$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-11.vpp"), baseaccess1_12$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-12.vpp"), baseaccess1_13$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-13.vpp"), baseaccess1_14$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-14.vpp"), baseaccess1_15$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-15.vpp"), baseaccess1_16$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-16.vpp"), baseaccess1_17$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-17.vpp"), baseaccess1_18$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-18.vpp"), baseaccess1_19$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-19.vpp"), baseaccess1_20$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-20.vpp"), baseaccess1_21$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-21.vpp"), baseaccess1_22$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-22.vpp"), baseaccess1_23$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-23.vpp"), baseaccess1_24$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-24.vpp"), baseaccess1_25$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-25.vpp"), baseaccess1_26$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-26.vpp"), baseaccess1_27$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-27.vpp"), baseaccess1_28$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-28.vpp"), baseaccess1_29$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-29.vpp"), baseaccess1_30$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-30.vpp"), baseaccess1_31$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-31.vpp"), baseaccess1_32$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-32.vpp"), baseaccess1_33$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-33.vpp"), baseaccess1_34$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-34.vpp"), baseaccess1_35$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-35.vpp"), baseaccess1_36$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-36.vpp"), baseaccess1_37$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-37.vpp"), baseaccess1_38$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-38.vpp"), baseaccess1_39$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-39.vpp"), baseaccess1_40$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-40.vpp"), baseaccess1_41$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-41.vpp"), baseaccess1_42$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-42.vpp"), baseaccess1_43$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-43.vpp"), baseaccess1_44$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-44.vpp"), baseaccess1_45$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-45.vpp"), baseaccess1_46$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-46.vpp"), baseaccess1_47$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-47.vpp"), baseaccess1_48$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-48.vpp"), baseaccess1_49$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-49.vpp"), baseaccess1_50$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-50.vpp"), baseaccess1_51$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-51.vpp"), baseaccess1_52$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-52.vpp"), baseaccess1_53$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-53.vpp"), baseaccess1_54$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-54.vpp"), baseaccess1_55$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-55.vpp"), baseaccess1_56$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-56.vpp"), baseaccess1_57$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-57.vpp"), baseaccess1_58$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-58.vpp"), baseaccess1_59$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-59.vpp"), baseaccess1_60$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-60.vpp"), baseaccess1_61$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-61.vpp"), baseaccess1_62$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-62.vpp"), baseaccess1_63$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-63.vpp"), baseaccess1_64$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-64.vpp"), baseaccess1_65$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-65.vpp"), baseaccess1_66$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-66.vpp"), baseaccess1_67$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-67.vpp"), baseaccess1_68$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-68.vpp"), baseaccess1_69$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-69.vpp"), baseaccess1_70$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-70.vpp"), baseaccess1_71$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-71.vpp"), baseaccess1_72$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-72.vpp"), baseaccess1_73$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-73.vpp"), baseaccess1_74$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-74.vpp"), baseaccess1_75$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-75.vpp"), baseaccess1_76$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-76.vpp"), baseaccess1_77$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-77.vpp"), baseaccess1_78$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-78.vpp"), baseaccess1_79$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-79.vpp"), baseaccess1_80$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-80.vpp"), baseaccess1_81$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-81.vpp"), baseaccess1_82$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-82.vpp"), baseaccess1_83$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-83.vpp"), baseaccess1_84$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-84.vpp"), baseaccess1_85$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-85.vpp"), baseaccess1_86$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-86.vpp"), baseaccess1_87$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-87.vpp"), baseaccess1_88$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-88.vpp"), baseaccess1_89$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-89.vpp"), baseaccess1_90$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-90.vpp"), baseaccess1_91$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-91.vpp"), baseaccess1_92$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-92.vpp"), baseaccess1_93$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-93.vpp"), baseaccess1_94$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-94.vpp"), baseaccess1_95$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-95.vpp"), baseaccess1_96$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-96.vpp"), baseaccess1_97$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-97.vpp"), baseaccess1_98$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-98.vpp"), baseaccess1_99$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess1/baseaccess1-99.vpp"), baseaccess2_00$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/baseaccess2/baseaccess2-00.vpp"), defexpr_06$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/defexpr/defexpr-06.vpp"), fcttypeinstexpr_01$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/fcttypeinstexpr/fcttypeinstexpr-01.vpp"), fcttypeinstexpr_03$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/fcttypeinstexpr/fcttypeinstexpr-03.vpp"), fcttypeinstexpr_04$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/fcttypeinstexpr/fcttypeinstexpr-04.vpp"), fcttypeinstexpr_05$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/fcttypeinstexpr/fcttypeinstexpr-05.vpp"), fcttypeinstexpr_06$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/fcttypeinstexpr/fcttypeinstexpr-06.vpp"), fcttypeinstexpr_10$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/fcttypeinstexpr/fcttypeinstexpr-10.vpp"), fcttypeinstexpr_15$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/fcttypeinstexpr/fcttypeinstexpr-15.vpp"), fcttypeinstexpr_17$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/fcttypeinstexpr/fcttypeinstexpr-17.vpp"), fcttypeinstexpr_21$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/fcttypeinstexpr/fcttypeinstexpr-21.vpp"), fcttypeinstexpr_22$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/fcttypeinstexpr/fcttypeinstexpr-22.vpp"), fcttypeinstexpr_23$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/fcttypeinstexpr/fcttypeinstexpr-23.vpp"), fcttypeinstexpr_24$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/fcttypeinstexpr/fcttypeinstexpr-24.vpp"), isofbaseclassexpr_02$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/isofbaseclassexpr/isofbaseclassexpr-02.vpp"), isofclassexpr_02$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/isofclassexpr/isofclassexpr-02.vpp"), isofclassexpr_07$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/isofclassexpr/isofclassexpr-07.vpp"), isofclassexpr_08$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/isofclassexpr/isofclassexpr-08.vpp"), newexpr_01$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/newexpr/newexpr-01.vpp"), samebaseclassexpr_01$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/samebaseclassexpr/samebaseclassexpr-01.vpp"), samebaseclassexpr_02$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/samebaseclassexpr/samebaseclassexpr-02.vpp"), samebaseclassexpr_05$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/samebaseclassexpr/samebaseclassexpr-05.vpp"), sameclassexpr_01$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/sameclassexpr/sameclassexpr-01.vpp"), sameclassexpr_02$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/sameclassexpr/sameclassexpr-02.vpp"), sameclassexpr_05$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/sameclassexpr/sameclassexpr-05.vpp"), selfexpr_01$vpp(
			"thirdpartytests/pp/pog/exprtest/PP/exprpp/selfexpr/selfexpr-01.vpp"), apply$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/apply/apply.vpp"), class_03$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/class/class-03.vpp"), constructor_07$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/constructor/constructor-07.vpp"), constructor_09$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/constructor/constructor-09.vpp"), fundefpp_02$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/fundefpp/fundefpp-02.vpp"), fundefpp$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/fundefpp/fundefpp.vpp"), instvar_01$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/instvar/instvar-01.vpp"), instvar_02$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/instvar/instvar-02.vpp"), instvar_03$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/instvar/instvar-03.vpp"), instvar_04$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/instvar/instvar-04.vpp"), lookup_01$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/lookup/lookup-01.vpp"), opdef_01$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/opdef/opdef-01.vpp"), opdef_02$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/opdef/opdef-02.vpp"), overload_01$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-01.vpp"), overload_02$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-02.vpp"), overload_12$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-12.vpp"), overload_13$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-13.vpp"), overload_16$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-16.vpp"), overload_17$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-17.vpp"), overload_19$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-19.vpp"), overload_20$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-20.vpp"), overload_21$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-21.vpp"), overload_23$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-23.vpp"), overload_24$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-24.vpp"), overload_25$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-25.vpp"), overload_26$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-26.vpp"), overload_27$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-27.vpp"), overload_28$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-28.vpp"), overload_29$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-29.vpp"), overload_30$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-30.vpp"), overload_35$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/overload/overload-35.vpp"), recfun_08$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/recfun/recfun-08.vpp"), recfun_15$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/recfun/recfun-15.vpp"), recfun_16$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/recfun/recfun-16.vpp"), recfun_30$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/recfun/recfun-30.vpp"), recfun_33$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/recfun/recfun-33.vpp"), recfun_37$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/recfun/recfun-37.vpp"), recfun_38$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/recfun/recfun-38.vpp"), recfun_39$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/recfun/recfun-39.vpp"), recfun_43$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/recfun/recfun-43.vpp"), recfun_45$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/recfun/recfun-45.vpp"), static_07$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/static/static-07.vpp"), static_08$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/static/static-08.vpp"), alwaysstmt_01$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/stmtpp/alwaysstmt/alwaysstmt-01.vpp"), assignstmt_01$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/stmtpp/assignstmt/assignstmt-01.vpp"), assignstmt_02$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/stmtpp/assignstmt/assignstmt-02.vpp"), casesstmt_01$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/stmtpp/casesstmt/casesstmt-01.vpp"), indexforloopstmt_02$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/stmtpp/indexforloopstmt/indexforloopstmt-02.vpp"), invokestmt_01$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/stmtpp/invokestmt/invokestmt-01.vpp"), invokestmt_02$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/stmtpp/invokestmt/invokestmt-02.vpp"), invokestmt_03$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/stmtpp/invokestmt/invokestmt-03.vpp"), invokestmt_04$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/stmtpp/invokestmt/invokestmt-04.vpp"), rectrapstmt_02$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/stmtpp/rectrapstmt/rectrapstmt-02.vpp"), specificationstmt_01$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/stmtpp/specificationstmt/specificationstmt-01.vpp"), trapstmt2$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/stmtpp/trapstmt/trapstmt2.vpp"), type_04$vpp(
			"thirdpartytests/pp/pog/fulltest/PP/type/type-04.vpp"), ;
	private String filePath;

	Thirdpartytests_pp(String fp)
	{
		this.filePath = fp;
	}

	public String getFolder()
	{
		return this.filePath;
	}
};
