// this file is automatically generated by treegen. do not modify!

package org.overture.tool.treegen.ast.itf;

public abstract interface ITreeGenAstShorthandDefinition extends ITreeGenAstDefinitions
{
	public abstract String getShorthandName();
	public abstract ITreeGenAstTypeSpecification getType();
}
