name: Java CI with Maven

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          server-id: github
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode clean verify -pl :javagen -am

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

      - name: Publish artifacts to GitHub Packages
        run: mvn --batch-mode -pl :javagen deploy:deploy-file@deploy-to-github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PACKAGES_REPO_URL: https://maven.pkg.github.com/${{ github.repository }}
  signal-vdm-vscode:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.repository }} == "overturetool/overture"
    
    steps:
      - name: Checking out
        uses: actions/checkout@v3
        
      - name: Getting POM artifact info
        id: get_artifact_info
        run: echo "version=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
        
      - name: Send repository dispatch http request to VDM-VSCode
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.VDM_VSCODE_PAT }}
          repository: glennlaursen/vdm-vscode
          event-type: new-jar
          client-payload: '{ "configId": "javagen", "version": "${{ steps.get_artifact_info.outputs.version }}" }'
